# Generated by root @ 2022-07-01 17:26:12.834356
execute at @e[tag=grow_home] run scoreboard players remove grow diy 1
execute at @e[tag=tick_home] run scoreboard players remove tick diy 1
function restworld:diy/_cur
