# Generated by root @ 2022-07-01 17:26:12.834054
execute at @e[tag=grow_home] run scoreboard players add grow diy 1
execute at @e[tag=tick_home] run scoreboard players add tick diy 1
function restworld:diy/_cur
