# Generated by root @ 2022-07-01 17:26:12.828339
setblock ~1 ~6 ~0 air
setblock ~1 ~6 ~0 oak_wall_sign[facing=east]{Text1: '{"bold": true, "italic": true, "text": "DIY:"}', Text2: '{"bold": true, "italic": true, "text": "Build Your"}', Text3: '{"bold": true, "italic": true, "text": "Own Sequence"}'}
