# Generated by root @ 2022-07-01 17:26:12.792464
execute at @e[tag=campfire_home] run function restworld:blocks/campfire_enter
execute at @e[tag=colorings_home] run function restworld:blocks/colorings_enter
execute at @e[tag=colored_beam_home] run function restworld:blocks/colored_beam_enter
weather clear
