# Generated by root @ 2022-07-01 17:26:12.660727
execute at @e[tag=blocks_home, tag=!no_expansion] run data merge block ~0 ~2 ~-1 {Text1: '"function restworld:blocks/toggle_expand"'}
execute at @e[tag=blocks_home, tag=!no_expansion] run data merge block ~0 ~2 ~1 {Text1: '"function restworld:blocks/toggle_expand"'}
execute at @e[tag=blocks_home, tag=no_expansion] run data merge block ~0 ~2 ~-1 {Text1: '"say Sorry, cannot expand this block"'}
execute at @e[tag=blocks_home, tag=no_expansion] run data merge block ~0 ~2 ~1 {Text1: '"say Sorry, cannot expand this block"'}
tag @e[tag=block_sign_home] add no_expansion
