# Generated by root @ 2022-07-01 17:26:12.666467
summon armor_stand ~0 ~2.5 ~0 {CustomName: '"Bricks"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_bricks, block_list_bricks_0_0, block_list_bricks_0_0_0]}
summon armor_stand ~0 ~2.74 ~0 {CustomName: '"Quartz Bricks"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_bricks, block_list_bricks_0_0, block_list_bricks_0_0_1]}
summon armor_stand ~0 ~2.98 ~0 {CustomName: '"Mud Bricks"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_bricks, block_list_bricks_0_0, block_list_bricks_0_0_2]}
summon armor_stand ~0 ~3.22 ~0 {CustomName: '"Deepslate Bricks"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_bricks, block_list_bricks_0_0, block_list_bricks_0_0_3]}
summon armor_stand ~0 ~3.46 ~0 {CustomName: '"Cracked Deepslate Bricks"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_bricks, block_list_bricks_0_0, block_list_bricks_0_0_4]}
summon armor_stand ~0 ~3.7 ~0 {CustomName: '"Deepslate Tiles"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_bricks, block_list_bricks_0_0, block_list_bricks_0_0_5]}
summon armor_stand ~0 ~3.94 ~0 {CustomName: '"Cracked Deepslate Tiles"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_bricks, block_list_bricks_0_0, block_list_bricks_0_0_6]}
summon armor_stand ~0 ~4.18 ~0 {CustomName: '"Prismarine Bricks"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_bricks, block_list_bricks_0_0, block_list_bricks_0_0_7]}
summon armor_stand ~0 ~4.42 ~0 {CustomName: '"Nether Bricks"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_bricks, block_list_bricks_0_0, block_list_bricks_0_0_8]}
summon armor_stand ~0 ~4.66 ~0 {CustomName: '"Cracked Nether Bricks"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_bricks, block_list_bricks_0_0, block_list_bricks_0_0_9]}
summon armor_stand ~0 ~4.9 ~0 {CustomName: '"Chiseled Nether Bricks"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_bricks, block_list_bricks_0_0, block_list_bricks_0_0_10]}
summon armor_stand ~0 ~5.14 ~0 {CustomName: '"Red Nether Bricks"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_bricks, block_list_bricks_0_0, block_list_bricks_0_0_11]}
