# Generated by root @ 2022-07-01 17:26:12.668055
summon armor_stand ~0 ~2.5 ~0 {CustomName: '"Campfire"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_campfire, block_list_campfire_0_0, block_list_campfire_0_0_0]}
summon armor_stand ~0 ~2.74 ~0 {CustomName: '"Campfire Unlit"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_campfire, block_list_campfire_0_0, block_list_campfire_0_0_1]}
summon armor_stand ~0 ~2.98 ~0 {CustomName: '"Soul Campfire"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_campfire, block_list_campfire_0_0, block_list_campfire_0_0_2]}
summon armor_stand ~0 ~3.22 ~0 {CustomName: '"Soul Campfire Unlit"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_campfire, block_list_campfire_0_0, block_list_campfire_0_0_3]}
