# Generated by root @ 2022-07-01 17:26:12.670148
summon armor_stand ~0 ~2.5 ~0 {CustomName: '"Clay"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_clay, block_list_clay_0_0, block_list_clay_0_0_0]}
summon armor_stand ~0 ~2.74 ~0 {CustomName: '"Mud"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_clay, block_list_clay_0_0, block_list_clay_0_0_1]}
summon armor_stand ~0 ~2.98 ~0 {CustomName: '"Muddy Mangrove Roots"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_clay, block_list_clay_0_0, block_list_clay_0_0_2]}
summon armor_stand ~0 ~3.22 ~0 {CustomName: '"Packed Mud"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_clay, block_list_clay_0_0, block_list_clay_0_0_3]}
