# Generated by root @ 2022-07-01 17:26:12.671646
summon armor_stand ~0 ~2.5 ~0 {CustomName: '"Cobblestone"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_cobble, block_list_cobble_0_0, block_list_cobble_0_0_0]}
summon armor_stand ~0 ~2.74 ~0 {CustomName: '"Mossy Cobblestone"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_cobble, block_list_cobble_0_0, block_list_cobble_0_0_1]}
summon armor_stand ~0 ~2.98 ~0 {CustomName: '"Cobbled Deepslate"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_cobble, block_list_cobble_0_0, block_list_cobble_0_0_2]}
