# Generated by root @ 2022-07-01 17:26:12.716012
summon armor_stand ~0 ~2.5 ~0 {CustomName: '"Copper Block"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_copper, block_list_copper_0_0, block_list_copper_0_0_0]}
summon armor_stand ~-3 ~2.5 ~0 {CustomName: '"Cut Copper"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_copper, "block_list_copper_-3_0", "block_list_copper_-3_0_0"]}
summon armor_stand ~0 ~2.74 ~0 {CustomName: '"Exposed Copper"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_copper, block_list_copper_0_0, block_list_copper_0_0_1]}
summon armor_stand ~-3 ~2.74 ~0 {CustomName: '"Exposed Cut Copper"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_copper, "block_list_copper_-3_0", "block_list_copper_-3_0_1"]}
summon armor_stand ~0 ~2.98 ~0 {CustomName: '"Weathered Copper"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_copper, block_list_copper_0_0, block_list_copper_0_0_2]}
summon armor_stand ~-3 ~2.98 ~0 {CustomName: '"Weathered Cut Copper"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_copper, "block_list_copper_-3_0", "block_list_copper_-3_0_2"]}
summon armor_stand ~0 ~3.22 ~0 {CustomName: '"Oxidized Copper"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_copper, block_list_copper_0_0, block_list_copper_0_0_3]}
summon armor_stand ~-3 ~3.22 ~0 {CustomName: '"Oxidized Cut Copper"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_copper, "block_list_copper_-3_0", "block_list_copper_-3_0_3"]}
