# Generated by root @ 2022-07-01 17:26:12.676247
summon armor_stand ~0 ~2.5 ~0 {CustomName: '"Dirt"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_dirt, block_list_dirt_0_0, block_list_dirt_0_0_0]}
summon armor_stand ~0 ~2.74 ~0 {CustomName: '"Coarse Dirt"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_dirt, block_list_dirt_0_0, block_list_dirt_0_0_1]}
summon armor_stand ~0 ~2.98 ~0 {CustomName: '"Rooted Dirt"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_dirt, block_list_dirt_0_0, block_list_dirt_0_0_2]}
summon armor_stand ~0 ~3.22 ~0 {CustomName: '"Farmland"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_dirt, block_list_dirt_0_0, block_list_dirt_0_0_3]}
