# Generated by root @ 2022-07-01 17:26:12.736419
setblock ~0 ~3 ~0 dripstone_block
setblock ~0 ~12 ~0 dripstone_block
setblock ~0 ~2 ~-1 air
setblock ~0 ~2 ~-1 oak_wall_sign[facing=north]{Text2: '"Dripstone"'}
