# Generated by root @ 2022-07-01 17:26:12.677779
summon armor_stand ~0 ~2.5 ~0 {CustomName: '"End Stone"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_end, block_list_end_0_0, block_list_end_0_0_0]}
summon armor_stand ~0 ~2.74 ~0 {CustomName: '"End Stone Bricks"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_end, block_list_end_0_0, block_list_end_0_0_1]}
