# Generated by root @ 2022-07-01 17:26:12.680724
summon armor_stand ~0 ~2.5 ~0 {CustomName: '"Glass"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_glass, block_list_glass_0_0, block_list_glass_0_0_0]}
summon armor_stand ~0 ~2.74 ~0 {CustomName: '"Tinted Glass"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_glass, block_list_glass_0_0, block_list_glass_0_0_1]}
