# Generated by root @ 2022-07-01 17:26:12.682201
summon armor_stand ~0 ~2.5 ~0 {CustomName: '"Ice"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_ice, block_list_ice_0_0, block_list_ice_0_0_0]}
summon armor_stand ~0 ~2.74 ~0 {CustomName: '"Packed Ice"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_ice, block_list_ice_0_0, block_list_ice_0_0_1]}
summon armor_stand ~0 ~2.98 ~0 {CustomName: '"Blue Ice"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_ice, block_list_ice_0_0, block_list_ice_0_0_2]}
