# Generated by root @ 2022-07-01 17:26:12.727288
summon armor_stand ~0 ~2.5 ~0 {CustomName: '"Fletching Table"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_job_sites_1, block_list_job_sites_1_0_0, block_list_job_sites_1_0_0_0]}
summon armor_stand ~0 ~2.74 ~0 {CustomName: '"Cartography Table"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_job_sites_1, block_list_job_sites_1_0_0, block_list_job_sites_1_0_0_1]}
summon armor_stand ~0 ~2.98 ~0 {CustomName: '"Smithing Table"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_job_sites_1, block_list_job_sites_1_0_0, block_list_job_sites_1_0_0_2]}
summon armor_stand ~0 ~3.22 ~0 {CustomName: '"Loom"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_job_sites_1, block_list_job_sites_1_0_0, block_list_job_sites_1_0_0_3]}
summon armor_stand ~0 ~3.46 ~0 {CustomName: '"Stonecutter"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_job_sites_1, block_list_job_sites_1_0_0, block_list_job_sites_1_0_0_4]}
