# Generated by root @ 2022-07-01 17:26:12.728857
summon armor_stand ~0 ~2.5 ~0 {CustomName: '"Blast Furnace"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_job_sites_2, block_list_job_sites_2_0_0, block_list_job_sites_2_0_0_0]}
summon armor_stand ~0 ~2.74 ~0 {CustomName: '"Blast Furnace"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_job_sites_2, block_list_job_sites_2_0_0, block_list_job_sites_2_0_0_1]}
summon armor_stand ~0 ~2.98 ~0 {CustomName: '"Smoker"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_job_sites_2, block_list_job_sites_2_0_0, block_list_job_sites_2_0_0_2]}
summon armor_stand ~0 ~3.22 ~0 {CustomName: '"Smoker"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_job_sites_2, block_list_job_sites_2_0_0, block_list_job_sites_2_0_0_3]}
summon armor_stand ~0 ~3.46 ~0 {CustomName: '"Barrel"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_job_sites_2, block_list_job_sites_2_0_0, block_list_job_sites_2_0_0_4]}
summon armor_stand ~0 ~3.7 ~0 {CustomName: '"Barrel"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_job_sites_2, block_list_job_sites_2_0_0, block_list_job_sites_2_0_0_5]}
summon armor_stand ~0 ~3.94 ~0 {CustomName: '"Lectern"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_job_sites_2, block_list_job_sites_2_0_0, block_list_job_sites_2_0_0_6]}
summon armor_stand ~0 ~4.18 ~0 {CustomName: '"Lectern"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_job_sites_2, block_list_job_sites_2_0_0, block_list_job_sites_2_0_0_7]}
