# Generated by root @ 2022-07-01 17:26:12.726987
setblock ~0 ~2 ~-1 air
setblock ~0 ~2 ~-1 oak_wall_sign[facing=north]
execute if score block_list blocks matches 0 run kill @e[tag=block_list_job_sites_1]
tag @e[tag=job_sites_1_home] add no_expansion
