# Generated by root @ 2022-07-01 17:26:12.687079
summon armor_stand ~0 ~2.5 ~0 {CustomName: '"Note Block"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_music, block_list_music_0_0, block_list_music_0_0_0]}
summon armor_stand ~0 ~2.74 ~0 {CustomName: '"Jukebox"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_music, block_list_music_0_0, block_list_music_0_0_1]}
summon armor_stand ~0 ~2.98 ~0 {CustomName: '"Jukebox Playing"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_music, block_list_music_0_0, block_list_music_0_0_2]}
