# Generated by root @ 2022-07-01 17:26:12.688592
summon armor_stand ~0 ~2.5 ~0 {CustomName: '"Netherrack"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_netherrack, block_list_netherrack_0_0, block_list_netherrack_0_0_0]}
summon armor_stand ~0 ~2.74 ~0 {CustomName: '"Warped Nylium"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_netherrack, block_list_netherrack_0_0, block_list_netherrack_0_0_1]}
summon armor_stand ~0 ~2.98 ~0 {CustomName: '"Crimson Nylium"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_netherrack, block_list_netherrack_0_0, block_list_netherrack_0_0_2]}
