# Generated by root @ 2022-07-01 17:26:12.690423
summon armor_stand ~0 ~2.5 ~0 {CustomName: '"Obsidian"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_obsidian, block_list_obsidian_0_0, block_list_obsidian_0_0_0]}
summon armor_stand ~0 ~2.74 ~0 {CustomName: '"Crying Obsidian"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_obsidian, block_list_obsidian_0_0, block_list_obsidian_0_0_1]}
