# Generated by root @ 2022-07-01 17:26:12.692282
summon armor_stand ~0 ~2.5 ~0 {CustomName: '"Prismarine"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_prismarine, block_list_prismarine_0_0, block_list_prismarine_0_0_0]}
summon armor_stand ~0 ~2.74 ~0 {CustomName: '"Prismarine Bricks"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_prismarine, block_list_prismarine_0_0, block_list_prismarine_0_0_1]}
summon armor_stand ~0 ~2.98 ~0 {CustomName: '"Dark Prismarine"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_prismarine, block_list_prismarine_0_0, block_list_prismarine_0_0_2]}
