# Generated by root @ 2022-07-01 17:26:12.693954
summon armor_stand ~0 ~2.5 ~0 {CustomName: '"Pumpkin"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_pumpkin, block_list_pumpkin_0_0, block_list_pumpkin_0_0_0]}
summon armor_stand ~0 ~2.74 ~0 {CustomName: '"Carved Pumpkin"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_pumpkin, block_list_pumpkin_0_0, block_list_pumpkin_0_0_1]}
summon armor_stand ~0 ~2.98 ~0 {CustomName: '"Jack O Lantern"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_pumpkin, block_list_pumpkin_0_0, block_list_pumpkin_0_0_2]}
