# Generated by root @ 2022-07-01 17:26:12.695466
summon armor_stand ~0 ~2.5 ~0 {CustomName: '"Purpur Block"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_purpur, block_list_purpur_0_0, block_list_purpur_0_0_0]}
summon armor_stand ~0 ~2.74 ~0 {CustomName: '"Purpur Pillar"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_purpur, block_list_purpur_0_0, block_list_purpur_0_0_1]}
