# Generated by root @ 2022-07-01 17:26:12.696997
summon armor_stand ~0 ~2.5 ~0 {CustomName: '"Quartz Block"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_quartz, block_list_quartz_0_0, block_list_quartz_0_0_0]}
summon armor_stand ~0 ~2.74 ~0 {CustomName: '"Smooth Quartz"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_quartz, block_list_quartz_0_0, block_list_quartz_0_0_1]}
summon armor_stand ~0 ~2.98 ~0 {CustomName: '"Quartz Pillar"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_quartz, block_list_quartz_0_0, block_list_quartz_0_0_2]}
summon armor_stand ~0 ~3.22 ~0 {CustomName: '"Chiseled Quartz Block"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_quartz, block_list_quartz_0_0, block_list_quartz_0_0_3]}
summon armor_stand ~0 ~3.46 ~0 {CustomName: '"Quartz Bricks"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_quartz, block_list_quartz_0_0, block_list_quartz_0_0_4]}
