# Generated by root @ 2022-07-01 17:26:12.698524
summon armor_stand ~0 ~2.5 ~0 {CustomName: '"Raw Iron Block"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_raw_metal, block_list_raw_metal_0_0, block_list_raw_metal_0_0_0]}
summon armor_stand ~0 ~2.74 ~0 {CustomName: '"Raw Copper Block"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_raw_metal, block_list_raw_metal_0_0, block_list_raw_metal_0_0_1]}
summon armor_stand ~0 ~2.98 ~0 {CustomName: '"Raw Gold Block"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_raw_metal, block_list_raw_metal_0_0, block_list_raw_metal_0_0_2]}
