# Generated by root @ 2022-07-01 17:26:12.703044
summon armor_stand ~0 ~2.5 ~0 {CustomName: '"Smooth Stone Slab"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_slabs, block_list_slabs_0_0, block_list_slabs_0_0_0]}
summon armor_stand ~0 ~2.74 ~0 {CustomName: '"Petrified Oak Slab"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_slabs, block_list_slabs_0_0, block_list_slabs_0_0_1]}
