# Generated by root @ 2022-07-01 17:26:12.704566
summon armor_stand ~0 ~2.5 ~0 {CustomName: '"Powder Snow"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_snow_blocks, block_list_snow_blocks_0_0, block_list_snow_blocks_0_0_0]}
summon armor_stand ~0 ~2.74 ~0 {CustomName: '"Snow Block"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_snow_blocks, block_list_snow_blocks_0_0, block_list_snow_blocks_0_0_1]}
