# Generated by root @ 2022-07-01 17:26:12.706289
summon armor_stand ~0 ~2.5 ~0 {CustomName: '"Grass Block"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_soil, block_list_soil_0_0, block_list_soil_0_0_0]}
summon armor_stand ~0 ~2.74 ~0 {CustomName: '"Podzol"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_soil, block_list_soil_0_0, block_list_soil_0_0_1]}
summon armor_stand ~0 ~2.98 ~0 {CustomName: '"Mycelium"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_soil, block_list_soil_0_0, block_list_soil_0_0_2]}
summon armor_stand ~0 ~3.22 ~0 {CustomName: '"Dirt Path"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_soil, block_list_soil_0_0, block_list_soil_0_0_3]}
