# Generated by root @ 2022-07-01 17:26:12.708263
summon armor_stand ~0 ~2.5 ~0 {CustomName: '"Soul Sand"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_soul_stuff, block_list_soul_stuff_0_0, block_list_soul_stuff_0_0_0]}
summon armor_stand ~0 ~2.74 ~0 {CustomName: '"Soul Soil"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_soul_stuff, block_list_soul_stuff_0_0, block_list_soul_stuff_0_0_1]}
