# Generated by root @ 2022-07-01 17:26:12.709751
summon armor_stand ~0 ~2.5 ~0 {CustomName: '"Sponge"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_sponge, block_list_sponge_0_0, block_list_sponge_0_0_0]}
summon armor_stand ~0 ~2.74 ~0 {CustomName: '"Wet Sponge"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_sponge, block_list_sponge_0_0, block_list_sponge_0_0_1]}
