# Generated by root @ 2022-07-01 17:26:12.772223
setblock ~3 ~4 ~5 air
setblock ~3 ~4 ~5 oak_wall_sign[facing=north]{Text2: '"Block"'}
setblock ~3 ~5 ~5 air
setblock ~3 ~5 ~5 oak_wall_sign[facing=north]{Text2: '"Double slab"'}
setblock ~1 ~2 ~-1 air
setblock ~1 ~2 ~-1 oak_wall_sign[facing=north]{Text2: '"Slabs & Stairs"'}
