# Generated by root @ 2022-07-01 17:26:12.711250
summon armor_stand ~0 ~2.5 ~0 {CustomName: '"Slime Block"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_sticky, block_list_sticky_0_0, block_list_sticky_0_0_0]}
summon armor_stand ~0 ~2.74 ~0 {CustomName: '"Honey block"', CustomNameVisible: true, Invisible: true, NoGravity: true, Tags: [block_list, block_list_sticky, block_list_sticky_0_0, block_list_sticky_0_0_1]}
