# Generated by root @ 2022-07-01 17:26:12.747284
tag @e[tag=ore_blocks_base] remove ore_blocks_home
tag @e[tag=ore_blocks_base] add deepslate_ore_blocks_home
execute at @e[tag=ore_blocks_base] run function restworld:blocks/deepslate_ore_blocks_cur
