# Generated by root @ 2022-07-01 17:26:12.746667
tag @e[tag=ore_blocks_base] add ore_blocks_home
tag @e[tag=ore_blocks_base] remove deepslate_ore_blocks_home
execute at @e[tag=ore_blocks_base] run function restworld:blocks/ore_blocks_cur
