# Generated by root @ 2022-07-01 17:26:12.718651
tag @e[tag=copper_base] remove copper_home
tag @e[tag=copper_base] add copper_waxed_home
execute at @e[tag=copper_base] run function restworld:blocks/waxed_copper_cur
