# Generated by root @ 2022-07-01 17:26:12.717928
tag @e[tag=copper_base] add copper_home
tag @e[tag=copper_base] remove copper_waxed_home
execute at @e[tag=copper_base] run function restworld:blocks/copper_cur
