# Generated by root @ 2022-07-01 17:26:12.802113
execute at @e[tag=fast_lights_home] run function restworld:center/fast_lights_cur
execute at @e[tag=main_lights_home] run function restworld:center/main_lights_cur
execute at @e[tag=slow_lights_home] run function restworld:center/slow_lights_cur
