# Generated by root @ 2022-07-01 17:26:12.800849
execute at @e[tag=fast_lights_home] run scoreboard players remove fast_lights center 1
execute at @e[tag=main_lights_home] run scoreboard players remove main_lights center 1
execute at @e[tag=slow_lights_home] run scoreboard players remove slow_lights center 1
function restworld:center/_cur
