# Generated by root @ 2022-07-01 17:26:12.799134
execute if score fast clocks matches 0 run function restworld:center/_fast
execute if score main clocks matches 0 run function restworld:center/_main
execute if score slow clocks matches 0 run function restworld:center/_slow
