# Generated by root @ 2022-07-01 17:26:12.798848
# Default home function
kill @e[tag=mobs_display_home]
execute positioned ~-0.5 ~0 ~0.5 run kill @e[type=armor_stand, dx=1,dy=2,dz=1]
summon armor_stand ~0 ~0.5 ~0 {NoGravity: true, Small: true, tags: [homer, center_homer], Tags: [mobs_display_home, center_home, homer]}
