kill @e[tag=effects_signer]
summon armor_stand ~1.000000 ~1.500000 ~-1.000000 {Tags:[effects_signer],Rotation:[90f,0f],ArmorItems:[{},{},{},{id:turtle_helmet,Count:1}]}
execute at @e[tag=effects_signer] run setblock ^-2 ^3 ^1 emerald_block
execute at @e[tag=effects_signer] run setblock ^-3 ^3 ^1 emerald_block
execute at @e[tag=effects_signer] run setblock ^-4 ^3 ^1 emerald_block
execute at @e[tag=effects_signer] run setblock ^-1 ^2 ^1 emerald_block
execute at @e[tag=effects_signer] run setblock ^-2 ^2 ^1 emerald_block
execute at @e[tag=effects_signer] run setblock ^-3 ^2 ^1 emerald_block
execute at @e[tag=effects_signer] run setblock ^-4 ^2 ^1 emerald_block
execute at @e[tag=effects_signer] run setblock ^-5 ^2 ^1 emerald_block
execute at @e[tag=effects_signer] run setblock ^-2 ^1 ^1 emerald_block
execute at @e[tag=effects_signer] run setblock ^-3 ^1 ^1 emerald_block
execute at @e[tag=effects_signer] run setblock ^-4 ^1 ^1 emerald_block
execute as @e[tag=effects_signer] run execute at @s run teleport @s ^-6 ^0 ^0 ~90 ~
execute at @e[tag=effects_signer] run setblock ^-2 ^3 ^1 emerald_block
execute at @e[tag=effects_signer] run setblock ^-3 ^3 ^1 emerald_block
execute at @e[tag=effects_signer] run setblock ^-4 ^3 ^1 emerald_block
execute at @e[tag=effects_signer] run setblock ^-1 ^2 ^1 emerald_block
execute at @e[tag=effects_signer] run setblock ^-2 ^2 ^1 emerald_block
execute at @e[tag=effects_signer] run setblock ^-3 ^2 ^1 emerald_block
execute at @e[tag=effects_signer] run setblock ^-4 ^2 ^1 emerald_block
execute at @e[tag=effects_signer] run setblock ^-5 ^2 ^1 emerald_block
execute at @e[tag=effects_signer] run setblock ^-2 ^1 ^1 emerald_block
execute at @e[tag=effects_signer] run setblock ^-3 ^1 ^1 emerald_block
execute at @e[tag=effects_signer] run setblock ^-4 ^1 ^1 emerald_block
execute as @e[tag=effects_signer] run execute at @s run teleport @s ^-6 ^0 ^0 ~90 ~
execute at @e[tag=effects_signer] run setblock ^-2 ^3 ^1 emerald_block
execute at @e[tag=effects_signer] run setblock ^-3 ^3 ^1 emerald_block
execute at @e[tag=effects_signer] run setblock ^-4 ^3 ^1 emerald_block
execute at @e[tag=effects_signer] run setblock ^-1 ^2 ^1 emerald_block
execute at @e[tag=effects_signer] run setblock ^-2 ^2 ^1 emerald_block
execute at @e[tag=effects_signer] run setblock ^-3 ^2 ^1 emerald_block
execute at @e[tag=effects_signer] run setblock ^-4 ^2 ^1 emerald_block
execute at @e[tag=effects_signer] run setblock ^-5 ^2 ^1 emerald_block
execute at @e[tag=effects_signer] run setblock ^-2 ^1 ^1 emerald_block
execute at @e[tag=effects_signer] run setblock ^-3 ^1 ^1 emerald_block
execute at @e[tag=effects_signer] run setblock ^-4 ^1 ^1 emerald_block
execute as @e[tag=effects_signer] run execute at @s run teleport @s ^-6 ^0 ^0 ~90 ~
kill @e[tag=effects_signer]
