kill @e[tag=effects_signer]
summon armor_stand ~1.000000 ~1.500000 ~-1.000000 {Tags:[effects_signer],Rotation:[90f,0f],ArmorItems:[{},{},{},{id:turtle_helmet,Count:1}]}
execute at @e[tag=effects_signer] run fill ^0 ^0 ^0 ^-6 ^4 ^-6 air replace oak_wall_sign
execute at @e[tag=effects_signer] run setblock ^-2 ^3 ^0 oak_wall_sign[facing=east]{Text2:"{\"text\":\"Absorption\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^-1 ^0 ^0 emerald_block\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p absorption 100000\"}}"} replace
execute at @e[tag=effects_signer] run setblock ^-3 ^3 ^0 oak_wall_sign[facing=east]{Text2:"{\"text\":\"Bad Luck\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^-1 ^0 ^0 emerald_block\"}}",Text3:"{\"text\":\"(Negative)\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p unluck 100000\"}}"} replace
execute at @e[tag=effects_signer] run setblock ^-4 ^3 ^0 oak_wall_sign[facing=east]{Text2:"{\"text\":\"Bad Omen\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^-1 ^0 ^0 emerald_block\"}}",Text3:"{\"text\":\"(Negative)\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p bad_omen 100000\"}}"} replace
execute at @e[tag=effects_signer] run setblock ^-1 ^2 ^0 oak_wall_sign[facing=east]{Text2:"{\"text\":\"Blindness\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^-1 ^0 ^0 emerald_block\"}}",Text3:"{\"text\":\"(Negative)\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p blindness 100000\"}}"} replace
execute at @e[tag=effects_signer] run setblock ^-2 ^2 ^0 oak_wall_sign[facing=east]{Text2:"{\"text\":\"Conduit Power\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^-1 ^0 ^0 emerald_block\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p conduit_power 100000\"}}"} replace
execute at @e[tag=effects_signer] run setblock ^-3 ^2 ^0 oak_wall_sign[facing=east]{Text2:"{\"text\":\"Darkness\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^-1 ^0 ^0 emerald_block\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p darkness 100000\"}}"} replace
execute at @e[tag=effects_signer] run setblock ^-4 ^2 ^0 oak_wall_sign[facing=east]{Text2:"{\"text\":\"Dolphin's Grace\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^-1 ^0 ^0 emerald_block\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p dolphins_grace 100000\"}}"} replace
execute at @e[tag=effects_signer] run setblock ^-5 ^2 ^0 oak_wall_sign[facing=east]{Text2:"{\"text\":\"Fire Resistance\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^-1 ^0 ^0 emerald_block\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p fire_resistance 100000\"}}"} replace
execute at @e[tag=effects_signer] run setblock ^-2 ^1 ^0 oak_wall_sign[facing=east]{Text2:"{\"text\":\"Glowing\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^-1 ^0 ^0 emerald_block\"}}",Text3:"{\"text\":\"(Neutral)\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p glowing 100000\"}}"} replace
execute at @e[tag=effects_signer] run setblock ^-3 ^1 ^0 oak_wall_sign[facing=east]{Text2:"{\"text\":\"Haste\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^-1 ^0 ^0 emerald_block\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p haste 100000\"}}"} replace
execute at @e[tag=effects_signer] run setblock ^-4 ^1 ^0 oak_wall_sign[facing=east]{Text2:"{\"text\":\"Health Boost\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^-1 ^0 ^0 emerald_block\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p health_boost 100000\"}}"} replace
execute as @e[tag=effects_signer] run execute at @s run teleport @s ^-6 ^0 ^0 ~90 ~
execute at @e[tag=effects_signer] run setblock ^-2 ^3 ^0 oak_wall_sign[facing=south]{Text2:"{\"text\":\"Hero\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^0 ^0 ^-1 emerald_block\"}}",Text3:"{\"text\":\"of the Village\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p hero_of_the_village 100000\"}}"} replace
execute at @e[tag=effects_signer] run setblock ^-3 ^3 ^0 oak_wall_sign[facing=south]{Text2:"{\"text\":\"Hunger\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^0 ^0 ^-1 emerald_block\"}}",Text3:"{\"text\":\"(Negative)\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p hunger 100000\"}}"} replace
execute at @e[tag=effects_signer] run setblock ^-4 ^3 ^0 oak_wall_sign[facing=south]{Text2:"{\"text\":\"Instant Damage\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^0 ^0 ^-1 emerald_block\"}}",Text3:"{\"text\":\"(Negative)\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p instant_damage 100000\"}}"} replace
execute at @e[tag=effects_signer] run setblock ^-1 ^2 ^0 oak_wall_sign[facing=south]{Text2:"{\"text\":\"Instant Health\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^0 ^0 ^-1 emerald_block\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p instant_health 100000\"}}"} replace
execute at @e[tag=effects_signer] run setblock ^-2 ^2 ^0 oak_wall_sign[facing=south]{Text2:"{\"text\":\"Invisibility\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^0 ^0 ^-1 emerald_block\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p invisibility 100000\"}}"} replace
execute at @e[tag=effects_signer] run setblock ^-3 ^2 ^0 oak_wall_sign[facing=south]{Text2:"{\"text\":\"Jump Boost\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^0 ^0 ^-1 emerald_block\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p jump_boost 100000\"}}"} replace
execute at @e[tag=effects_signer] run setblock ^-4 ^2 ^0 oak_wall_sign[facing=south]{Text2:"{\"text\":\"Levitation\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^0 ^0 ^-1 emerald_block\"}}",Text3:"{\"text\":\"(Negative)\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p levitation 100000\"}}"} replace
execute at @e[tag=effects_signer] run setblock ^-5 ^2 ^0 oak_wall_sign[facing=south]{Text2:"{\"text\":\"Luck\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^0 ^0 ^-1 emerald_block\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p luck 100000\"}}"} replace
execute at @e[tag=effects_signer] run setblock ^-2 ^1 ^0 oak_wall_sign[facing=south]{Text2:"{\"text\":\"Mining Fatigue\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^0 ^0 ^-1 emerald_block\"}}",Text3:"{\"text\":\"(Negative)\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p mining_fatigue 100000\"}}"} replace
execute at @e[tag=effects_signer] run setblock ^-3 ^1 ^0 oak_wall_sign[facing=south]{Text2:"{\"text\":\"Nausea\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^0 ^0 ^-1 emerald_block\"}}",Text3:"{\"text\":\"(Negative)\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p nausea 100000\"}}"} replace
execute at @e[tag=effects_signer] run setblock ^-4 ^1 ^0 oak_wall_sign[facing=south]{Text2:"{\"text\":\"Night Vision\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^0 ^0 ^-1 emerald_block\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p night_vision 100000\"}}"} replace
execute as @e[tag=effects_signer] run execute at @s run teleport @s ^-6 ^0 ^0 ~90 ~
execute at @e[tag=effects_signer] run setblock ^-2 ^3 ^0 oak_wall_sign[facing=west]{Text2:"{\"text\":\"Poison\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}",Text3:"{\"text\":\"(Negative)\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p poison 100000\"}}"} replace
execute at @e[tag=effects_signer] run setblock ^-3 ^3 ^0 oak_wall_sign[facing=west]{Text2:"{\"text\":\"Regeneration\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p regeneration 100000\"}}"} replace
execute at @e[tag=effects_signer] run setblock ^-4 ^3 ^0 oak_wall_sign[facing=west]{Text2:"{\"text\":\"Resistance\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p resistance 100000\"}}"} replace
execute at @e[tag=effects_signer] run setblock ^-1 ^2 ^0 oak_wall_sign[facing=west]{Text2:"{\"text\":\"Saturation\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p saturation 100000\"}}"} replace
execute at @e[tag=effects_signer] run setblock ^-2 ^2 ^0 oak_wall_sign[facing=west]{Text2:"{\"text\":\"Slow Falling\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p slow_falling 100000\"}}"} replace
execute at @e[tag=effects_signer] run setblock ^-3 ^2 ^0 oak_wall_sign[facing=west]{Text2:"{\"text\":\"Slowness\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}",Text3:"{\"text\":\"(Negative)\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p slowness 100000\"}}"} replace
execute at @e[tag=effects_signer] run setblock ^-4 ^2 ^0 oak_wall_sign[facing=west]{Text2:"{\"text\":\"Speed\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p speed 100000\"}}"} replace
execute at @e[tag=effects_signer] run setblock ^-5 ^2 ^0 oak_wall_sign[facing=west]{Text2:"{\"text\":\"Strength\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p strength 100000\"}}"} replace
execute at @e[tag=effects_signer] run setblock ^-2 ^1 ^0 oak_wall_sign[facing=west]{Text2:"{\"text\":\"Water Breathing\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p water_breathing 100000\"}}"} replace
execute at @e[tag=effects_signer] run setblock ^-3 ^1 ^0 oak_wall_sign[facing=west]{Text2:"{\"text\":\"Weakness\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}",Text3:"{\"text\":\"(Negative)\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p weakness 100000\"}}"} replace
execute at @e[tag=effects_signer] run setblock ^-4 ^1 ^0 oak_wall_sign[facing=west]{Text2:"{\"text\":\"Wither\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"setblock ^1 ^0 ^0 emerald_block\"}}",Text3:"{\"text\":\"(Negative)\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"effect give @p wither 100000\"}}"} replace
execute as @e[tag=effects_signer] run execute at @s run teleport @s ^-6 ^0 ^0 ~90 ~
kill @e[tag=effects_signer]
