# Generated by root @ 2022-07-01 17:26:13.004116
execute at @e[tag=all_sand_home] run scoreboard players remove all_sand materials 1
execute at @e[tag=arrows_home] run scoreboard players remove arrows materials 1
execute at @e[tag=experience_orbs_home] run scoreboard players remove experience_orbs materials 1
execute at @e[tag=ores_home] run scoreboard players remove ores materials 1
execute at @e[tag=basic_home] run scoreboard players remove basic materials 1
execute at @e[tag=panes_home] run scoreboard players remove panes materials 1
execute at @e[tag=fences_home] run scoreboard players remove fences materials 1
execute at @e[tag=walls_home] run scoreboard players remove walls materials 1
execute at @e[tag=wood_home] run scoreboard players remove wood materials 1
function restworld:materials/_cur
