# Generated by root @ 2022-07-01 17:26:13.003745
execute at @e[tag=all_sand_home] run scoreboard players add all_sand materials 1
execute at @e[tag=arrows_home] run scoreboard players add arrows materials 1
execute at @e[tag=experience_orbs_home] run scoreboard players add experience_orbs materials 1
execute at @e[tag=ores_home] run scoreboard players add ores materials 1
execute at @e[tag=basic_home] run scoreboard players add basic materials 1
execute at @e[tag=panes_home] run scoreboard players add panes materials 1
execute at @e[tag=fences_home] run scoreboard players add fences materials 1
execute at @e[tag=walls_home] run scoreboard players add walls materials 1
execute at @e[tag=wood_home] run scoreboard players add wood materials 1
function restworld:materials/_cur
