# Generated by root @ 2022-07-01 17:26:13.002223
execute if score main clocks matches 0 run function restworld:materials/_main
execute if score fast clocks matches 0 run function restworld:materials/_fast
