# Generated by root @ 2022-07-01 17:26:12.986764
execute at @e[tag=basic_home] run function restworld:materials/basic_cur
execute at @e[tag=basic_home] run function restworld:materials/basic_finish_main
