# Generated by root @ 2022-07-01 17:26:12.976231
setblock ~-1 ~6 ~0 air
setblock ~-1 ~6 ~0 oak_wall_sign[facing=west]{Text1: '{"bold": true, "italic": true, "text": "Materials"}', Text2: '{"bold": true, "italic": true, "text": "& Tools,"}', Text3: '{"bold": true, "italic": true, "text": "Time, GUI,"}', Text4: '{"bold": true, "italic": true, "text": "Redstone"}'}
