# Generated by root @ 2022-07-01 17:26:12.992256
kill @e[tag=which_fencelike_home]
execute at @e[tag=fencelike_home] positioned ~1 ~-1 ~0 run function restworld:materials/walls_home
tag @e[tag=walls_home] add which_fencelike_home
execute at @e[tag=walls_home] run function restworld:materials/walls_cur
