# Generated by root @ 2022-07-01 17:26:12.826637
execute at @e[tag=beacon_home] run scoreboard players remove beacon containers 1
execute at @e[tag=bossbar_color_home] run scoreboard players remove bossbar_color containers 1
execute at @e[tag=bossbar_style_home] run scoreboard players remove bossbar_style containers 1
execute at @e[tag=bossbar_value_home] run scoreboard players remove bossbar_value containers 1
execute at @e[tag=brewing_rotate_home] run scoreboard players remove brewing_rotate containers 1
execute at @e[tag=strength_llama_home] run scoreboard players remove strength_llama containers 1
execute at @e[tag=experience_home] run scoreboard players remove experience containers 1
execute at @e[tag=survival_home] run scoreboard players remove survival containers 1
function restworld:containers/_cur
