# Generated by root @ 2022-07-01 17:26:12.827916
execute at @e[tag=beacon_home] run function restworld:containers/beacon_exit
execute at @e[tag=bossbar_home] run function restworld:containers/bossbar_exit
execute at @e[tag=item_home] run function restworld:containers/item_exit
