# Generated by root @ 2022-07-01 17:26:12.825438
execute at @e[tag=bossbar_color_home] run function restworld:containers/bossbar_color_main
execute at @e[tag=bossbar_style_home] run function restworld:containers/bossbar_style_main
execute at @e[tag=bossbar_value_home] run function restworld:containers/bossbar_value_main
execute at @e[tag=brewing_rotate_home] run function restworld:containers/brewing_rotate_main
execute at @e[tag=strength_llama_home] run function restworld:containers/strength_llama_main
execute at @e[tag=experience_home] run function restworld:containers/experience_main
execute at @e[tag=survival_home] run function restworld:containers/survival_main
