# Generated by root @ 2022-07-01 17:26:12.824704
execute if score slow clocks matches 0 run function restworld:containers/_slow
execute if score main clocks matches 0 run function restworld:containers/_main
execute if score fast clocks matches 0 run function restworld:containers/_fast
