# Generated by root @ 2022-07-01 17:26:12.811265
function restworld:containers/switch_brewing_off
execute positioned ~1 ~1 ~-1 run kill @e[type=item_frame, tag=label, sort=nearest, distance=..2, limit=1]
summon item_frame ~1 ~1 ~-1 {Facing: 1, Fixed: true, Invisible: true, Item: {Count: 1, id: stone_button, tag: {display: {Name: '{"text": "Brew"}'}}}, Tags: [label]}
