# Generated by root @ 2022-07-01 17:26:12.814114
summon llama ~0 ~2 ~0 {ChestedHorse: true, CustomName: '"Llama"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [carrier, containers, strength_llama, llama, adult], Tame: true, Variant: 2}
summon donkey ~0 ~2 ~3 {ChestedHorse: true, CustomName: '"Donkey"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [carrier, containers, donkey, adult], Tame: true, Variant: 2}
