# Generated by root @ 2022-07-01 17:26:12.802847
setblock ~0 ~6 ~-1 air
setblock ~0 ~6 ~-1 oak_wall_sign[facing=north]{Text1: '{"bold": true, "italic": true, "text": "GUI,"}', Text2: '{"bold": true, "italic": true, "text": "Containers,"}', Text3: '{"bold": true, "italic": true, "text": "Items"}'}
