# Generated by root @ 2022-07-01 17:26:12.816684
summon villager ~0 ~2 ~0 {CanPickUpLoot: false, CustomName: '"Villager"', NoAI: true, PersistenceRequired: true, Rotation: [180.0f, 0.0f], Silent: true, Tags: [trades, containers, villager, adult], VillagerData: {level: 3, profession: farmer}}
function restworld:containers/experience_cur
