# Generated by root @ 2022-07-01 17:26:12.813539
item replace block ~0 ~2 ~0 container.3 with air
item replace block ~0 ~2 ~0 container.4 with air
data merge block ~0 ~2 ~0 {Fuel: 0}
kill @e[tag=brewing_run_home]
