# Generated by root @ 2022-07-01 17:26:12.806590
execute store result score toggle_bossbar containers run bossbar get restworld:bossbar visible
execute if score toggle_bossbar containers matches 0 run bossbar set restworld:bossbar visible true
execute if score toggle_bossbar containers matches 1 run bossbar set restworld:bossbar visible false
