function restworld:banners/banner_controls_remove
function restworld:global/clock_off



setblock ~0 ~3 ~1 oak_wall_sign[facing=south]{Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_color_action_home] positioned ~0 ~2 ~0 run scoreboard players set banner_color funcs 0\"}}",Text2:"{\"text\":\"White\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_color_action_home] run function restworld:banners/banner_color_cur\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_ink_action_home] positioned ~0 ~2 ~0 run scoreboard players set banner_ink funcs 0\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_ink_action_home] run function restworld:banners/banner_ink_cur\"}}"}


setblock ~1 ~3 ~1 oak_wall_sign[facing=south]{Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_color_action_home] positioned ~0 ~2 ~0 run scoreboard players set banner_color funcs 1\"}}",Text2:"{\"text\":\"Orange\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_color_action_home] run function restworld:banners/banner_color_cur\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_ink_action_home] positioned ~0 ~2 ~0 run scoreboard players set banner_ink funcs 1\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_ink_action_home] run function restworld:banners/banner_ink_cur\"}}"}


setblock ~2 ~3 ~1 oak_wall_sign[facing=south]{Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_color_action_home] positioned ~0 ~2 ~0 run scoreboard players set banner_color funcs 2\"}}",Text2:"{\"text\":\"Magenta\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_color_action_home] run function restworld:banners/banner_color_cur\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_ink_action_home] positioned ~0 ~2 ~0 run scoreboard players set banner_ink funcs 2\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_ink_action_home] run function restworld:banners/banner_ink_cur\"}}"}


setblock ~3 ~3 ~1 oak_wall_sign[facing=south]{Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_color_action_home] positioned ~0 ~2 ~0 run scoreboard players set banner_color funcs 3\"}}",Text2:"{\"text\":\"Light Blue\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_color_action_home] run function restworld:banners/banner_color_cur\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_ink_action_home] positioned ~0 ~2 ~0 run scoreboard players set banner_ink funcs 3\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_ink_action_home] run function restworld:banners/banner_ink_cur\"}}"}


setblock ~5 ~3 ~1 oak_wall_sign[facing=south]{Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_color_action_home] positioned ~0 ~2 ~0 run scoreboard players set banner_color funcs 4\"}}",Text2:"{\"text\":\"Yellow\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_color_action_home] run function restworld:banners/banner_color_cur\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_ink_action_home] positioned ~0 ~2 ~0 run scoreboard players set banner_ink funcs 4\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_ink_action_home] run function restworld:banners/banner_ink_cur\"}}"}


setblock ~6 ~3 ~1 oak_wall_sign[facing=south]{Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_color_action_home] positioned ~0 ~2 ~0 run scoreboard players set banner_color funcs 5\"}}",Text2:"{\"text\":\"Lime\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_color_action_home] run function restworld:banners/banner_color_cur\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_ink_action_home] positioned ~0 ~2 ~0 run scoreboard players set banner_ink funcs 5\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_ink_action_home] run function restworld:banners/banner_ink_cur\"}}"}


setblock ~7 ~3 ~1 oak_wall_sign[facing=south]{Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_color_action_home] positioned ~0 ~2 ~0 run scoreboard players set banner_color funcs 6\"}}",Text2:"{\"text\":\"Pink\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_color_action_home] run function restworld:banners/banner_color_cur\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_ink_action_home] positioned ~0 ~2 ~0 run scoreboard players set banner_ink funcs 6\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_ink_action_home] run function restworld:banners/banner_ink_cur\"}}"}


setblock ~8 ~3 ~1 oak_wall_sign[facing=south]{Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_color_action_home] positioned ~0 ~2 ~0 run scoreboard players set banner_color funcs 7\"}}",Text2:"{\"text\":\"Gray\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_color_action_home] run function restworld:banners/banner_color_cur\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_ink_action_home] positioned ~0 ~2 ~0 run scoreboard players set banner_ink funcs 7\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_ink_action_home] run function restworld:banners/banner_ink_cur\"}}"}


setblock ~0 ~2 ~2 oak_wall_sign[facing=south]{Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_color_action_home] positioned ~0 ~2 ~0 run scoreboard players set banner_color funcs 8\"}}",Text2:"{\"text\":\"Light Gray\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_color_action_home] run function restworld:banners/banner_color_cur\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_ink_action_home] positioned ~0 ~2 ~0 run scoreboard players set banner_ink funcs 8\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_ink_action_home] run function restworld:banners/banner_ink_cur\"}}"}


setblock ~1 ~2 ~2 oak_wall_sign[facing=south]{Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_color_action_home] positioned ~0 ~2 ~0 run scoreboard players set banner_color funcs 9\"}}",Text2:"{\"text\":\"Cyan\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_color_action_home] run function restworld:banners/banner_color_cur\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_ink_action_home] positioned ~0 ~2 ~0 run scoreboard players set banner_ink funcs 9\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_ink_action_home] run function restworld:banners/banner_ink_cur\"}}"}


setblock ~2 ~2 ~2 oak_wall_sign[facing=south]{Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_color_action_home] positioned ~0 ~2 ~0 run scoreboard players set banner_color funcs 10\"}}",Text2:"{\"text\":\"Purple\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_color_action_home] run function restworld:banners/banner_color_cur\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_ink_action_home] positioned ~0 ~2 ~0 run scoreboard players set banner_ink funcs 10\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_ink_action_home] run function restworld:banners/banner_ink_cur\"}}"}


setblock ~3 ~2 ~2 oak_wall_sign[facing=south]{Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_color_action_home] positioned ~0 ~2 ~0 run scoreboard players set banner_color funcs 11\"}}",Text2:"{\"text\":\"Blue\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_color_action_home] run function restworld:banners/banner_color_cur\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_ink_action_home] positioned ~0 ~2 ~0 run scoreboard players set banner_ink funcs 11\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_ink_action_home] run function restworld:banners/banner_ink_cur\"}}"}


setblock ~5 ~2 ~2 oak_wall_sign[facing=south]{Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_color_action_home] positioned ~0 ~2 ~0 run scoreboard players set banner_color funcs 12\"}}",Text2:"{\"text\":\"Brown\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_color_action_home] run function restworld:banners/banner_color_cur\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_ink_action_home] positioned ~0 ~2 ~0 run scoreboard players set banner_ink funcs 12\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_ink_action_home] run function restworld:banners/banner_ink_cur\"}}"}


setblock ~6 ~2 ~2 oak_wall_sign[facing=south]{Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_color_action_home] positioned ~0 ~2 ~0 run scoreboard players set banner_color funcs 13\"}}",Text2:"{\"text\":\"Green\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_color_action_home] run function restworld:banners/banner_color_cur\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_ink_action_home] positioned ~0 ~2 ~0 run scoreboard players set banner_ink funcs 13\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_ink_action_home] run function restworld:banners/banner_ink_cur\"}}"}


setblock ~7 ~2 ~2 oak_wall_sign[facing=south]{Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_color_action_home] positioned ~0 ~2 ~0 run scoreboard players set banner_color funcs 14\"}}",Text2:"{\"text\":\"Red\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_color_action_home] run function restworld:banners/banner_color_cur\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_ink_action_home] positioned ~0 ~2 ~0 run scoreboard players set banner_ink funcs 14\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_ink_action_home] run function restworld:banners/banner_ink_cur\"}}"}


setblock ~8 ~2 ~2 oak_wall_sign[facing=south]{Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_color_action_home] positioned ~0 ~2 ~0 run scoreboard players set banner_color funcs 15\"}}",Text2:"{\"text\":\"Black\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_color_action_home] run function restworld:banners/banner_color_cur\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_ink_action_home] positioned ~0 ~2 ~0 run scoreboard players set banner_ink funcs 15\"}}",Text4:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banner_ink_action_home] run function restworld:banners/banner_ink_cur\"}}"}

setblock ~4 ~3 ~1 dark_oak_wall_sign[facing=south]{Color:white,Text2:"{\"text\":\"Set Banner\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banners_action_home] positioned ~0 ~2 ~0 run function restworld:banners/switch_to_color\"}}",Text3:"\"Color\""}
setblock ~4 ~2 ~2 dark_oak_wall_sign[facing=south]{Color:white,Text2:"{\"text\":\"Set Ink\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=banners_action_home] positioned ~0 ~2 ~0 run function restworld:banners/switch_to_ink\"}}",Text3:"\"Color\""}
