# Generated by root @ 2022-07-01 17:26:12.896520
execute at @e[tag=animal_home] run function restworld:particles/animal_cur
execute at @e[tag=falling_dust_change_home] run function restworld:particles/falling_dust_change_cur
execute at @e[tag=firework_change_home] run function restworld:particles/firework_change_cur
execute at @e[tag=nautilus_change_home] run function restworld:particles/nautilus_change_cur
execute at @e[tag=vibration_run_home] run function restworld:particles/vibration_run_cur
execute at @e[tag=small_animal_home] run function restworld:particles/small_animal_cur
execute at @e[tag=squid_ink_run_home] run function restworld:particles/squid_ink_run_cur
execute at @e[tag=villager_home] run function restworld:particles/villager_cur
execute at @e[tag=wax_on_run_home] run function restworld:particles/wax_on_run_cur
