# Generated by root @ 2022-07-01 17:26:12.894962
execute at @e[tag=animal_home] run scoreboard players add animal particles 1
execute at @e[tag=falling_dust_change_home] run scoreboard players add falling_dust_change particles 1
execute at @e[tag=firework_change_home] run scoreboard players add firework_change particles 1
execute at @e[tag=nautilus_change_home] run scoreboard players add nautilus_change particles 1
execute at @e[tag=vibration_run_home] run scoreboard players add vibration_run particles 1
execute at @e[tag=small_animal_home] run scoreboard players add small_animal particles 1
execute at @e[tag=squid_ink_run_home] run scoreboard players add squid_ink_run particles 1
execute at @e[tag=villager_home] run scoreboard players add villager particles 1
execute at @e[tag=wax_on_run_home] run scoreboard players add wax_on_run particles 1
function restworld:particles/_cur
