# Generated by root @ 2022-07-01 17:26:12.846346
execute if score main clocks matches 0 at @e[tag=particles_action_home] positioned ~0 ~2 ~0 run particle ambient_entity_effect ~0 ~0 ~0 0.5 5 0.5 1 500
