# Generated by root @ 2022-07-01 17:26:12.854574
kill @e[tag=particle_dragonball]
summon dragon_fireball ~0 ~4 ~4 {direction: "{0.0}", ExplosionPower: 0, power: "{0.0, -0.05}", Tags: [particle_dragonball, particler]}
