# Generated by root @ 2022-07-01 17:26:12.856168
fill ~3 ~5 ~3 ~-3 ~5 ~-3 structure_void
fill ~2 ~4 ~2 ~-2 ~4 ~-2 stone
setblock ~2 ~4 ~2 dripstone_block
setblock ~-2 ~4 ~2 dripstone_block
setblock ~2 ~4 ~-2 dripstone_block
setblock ~-2 ~4 ~-2 dripstone_block
setblock ~2 ~3 ~2 pointed_dripstone[thickness=base,vertical_direction=down]
setblock ~-2 ~3 ~2 pointed_dripstone[thickness=base,vertical_direction=down]
setblock ~2 ~3 ~-2 pointed_dripstone[thickness=base,vertical_direction=down]
setblock ~-2 ~3 ~-2 pointed_dripstone[thickness=base,vertical_direction=down]
fill ~2 ~5 ~2 ~-2 ~5 ~-2 water
