# Generated by root @ 2022-07-01 17:26:12.854866
fill ~2 ~3 ~2 ~-2 ~3 ~-2 beehive[honey_level=5, facing=south]
fill ~2 ~3 ~-2 ~-2 ~3 ~-2 beehive[honey_level=5, facing=north]
fill ~2 ~3 ~-1 ~2 ~3 ~1 beehive[honey_level=5, facing=east]
fill ~-2 ~3 ~-1 ~-2 ~3 ~1 beehive[honey_level=5, facing=west]
