# Generated by root @ 2022-07-01 17:26:12.856573
fill ~2 ~0 ~2 ~-2 ~0 ~-2 redstone_wire
fill ~1 ~0 ~1 ~-1 ~0 ~-1 air
setblock ~-1 ~0 ~-2 air
setblock ~-2 ~0 ~-2 redstone_block
setblock ~-2 ~0 ~-1 repeater
