# Generated by root @ 2022-07-01 17:26:12.877714
particle sculk_charge -0.183 ~-1 ~0.3 ~-1
particle sculk_charge -0.11 ~0 ~0.3 ~-1
particle sculk_charge -0.211 ~-1 ~0.3 ~1
particle sculk_charge 0.15 ~0 ~0.5 ~-1
particle sculk_charge -0.483 ~0 ~0.5 ~1
particle sculk_charge -0.077 ~1 ~0.5 ~0
