# Generated by root @ 2022-07-01 17:26:12.879322
particle shriek 0 ~0 ~1 ~0
particle shriek 7 ~0 ~1 ~0
particle shriek 14 ~0 ~1 ~0
particle shriek 21 ~0 ~1 ~0
particle shriek 28 ~0 ~1 ~0
particle shriek 35 ~0 ~1 ~0
particle shriek 42 ~0 ~1 ~0
particle shriek 49 ~0 ~1 ~0
