scoreboard players set amethyst funcs 0
scoreboard players set anvil funcs 0
scoreboard players set bee_nest funcs 0
scoreboard players set beehive funcs 0
scoreboard players set bell funcs 0
scoreboard players set blocks_room funcs 0
scoreboard players set blocks_sign funcs 0
scoreboard players set brewing_stand funcs 0
scoreboard players set bricks funcs 0
scoreboard players set cake funcs 0
scoreboard players set campfire funcs 0
scoreboard players set cauldron funcs 0
scoreboard players set chest funcs 0
scoreboard players set clay funcs 0
scoreboard players set cobble funcs 0
scoreboard players set colored_beam funcs 0
scoreboard players set colorings funcs 0
scoreboard players set command_blocks funcs 0
scoreboard players set composter funcs 0
scoreboard players set copper funcs 0
scoreboard players set deepslate funcs 0
scoreboard players set dirt funcs 0
scoreboard players set dripstone funcs 0
scoreboard players set end funcs 0
scoreboard players set expand funcs 0
scoreboard players set fire funcs 0
scoreboard players set frosted_ice funcs 0
scoreboard players set glass funcs 0
scoreboard players set grindstone funcs 0
scoreboard players set ice funcs 0
scoreboard players set item_frame funcs 0
scoreboard players set job_sites_1 funcs 0
scoreboard players set job_sites_2 funcs 0
scoreboard players set lantern funcs 0
scoreboard players set light funcs 0
scoreboard players set lighting funcs 0
scoreboard players set music funcs 0
scoreboard players set netherrack funcs 0
scoreboard players set obsidian funcs 0
scoreboard players set ore_blocks funcs 0
scoreboard players set prismarine funcs 0
scoreboard players set pumpkin funcs 0
scoreboard players set purpur funcs 0
scoreboard players set quartz funcs 0
scoreboard players set raw_metal funcs 0
scoreboard players set respawn_anchor funcs 0
scoreboard players set sandstone funcs 0
scoreboard players set scaffolding funcs 0
scoreboard players set sculk_blocks funcs 0
scoreboard players set slabs funcs 0
scoreboard players set snow funcs 0
scoreboard players set snow_blocks funcs 0
scoreboard players set soil funcs 0
scoreboard players set soul_stuff funcs 0
scoreboard players set spawner funcs 0
scoreboard players set sponge funcs 0
scoreboard players set stepable funcs 0
scoreboard players set sticky funcs 0
scoreboard players set stone funcs 0
scoreboard players set stone_bricks funcs 0
scoreboard players set structure_blocks funcs 0
scoreboard players set tnt funcs 0
scoreboard players set torches funcs 0
scoreboard players set wood_blocks funcs 0


execute at @e[tag=campfire_home] run function restworld:blocks/campfire_enter
execute at @e[tag=colored_beam_home] run function restworld:blocks/colored_beam_enter
execute at @e[tag=colorings_home] run function restworld:blocks/colorings_enter


weather clear
