scoreboard players set amethyst funcs 0
scoreboard players set anvil funcs 0
scoreboard players set bee_nest funcs 0
scoreboard players set beehive funcs 0
scoreboard players set bell funcs 0
scoreboard players set blocks_room funcs 0
scoreboard players set blocks_sign funcs 0
scoreboard players set brewing_stand funcs 0
scoreboard players set bricks funcs 0
scoreboard players set cake funcs 0
scoreboard players set campfire funcs 0
scoreboard players set cauldron funcs 0
scoreboard players set chest funcs 0
scoreboard players set clay funcs 0
scoreboard players set cobble funcs 0
scoreboard players set colored_beam funcs 0
scoreboard players set colorings funcs 0
scoreboard players set command_blocks funcs 0
scoreboard players set composter funcs 0
scoreboard players set copper funcs 0
scoreboard players set deepslate funcs 0
scoreboard players set dirt funcs 0
scoreboard players set dripstone funcs 0
scoreboard players set end funcs 0
scoreboard players set expand funcs 0
scoreboard players set fire funcs 0
scoreboard players set frosted_ice funcs 0
scoreboard players set glass funcs 0
scoreboard players set grindstone funcs 0
scoreboard players set ice funcs 0
scoreboard players set item_frame funcs 0
scoreboard players set job_sites_1 funcs 0
scoreboard players set job_sites_2 funcs 0
scoreboard players set lantern funcs 0
scoreboard players set light funcs 0
scoreboard players set lighting funcs 0
scoreboard players set music funcs 0
scoreboard players set netherrack funcs 0
scoreboard players set obsidian funcs 0
scoreboard players set ore_blocks funcs 0
scoreboard players set prismarine funcs 0
scoreboard players set pumpkin funcs 0
scoreboard players set purpur funcs 0
scoreboard players set quartz funcs 0
scoreboard players set raw_metal funcs 0
scoreboard players set respawn_anchor funcs 0
scoreboard players set sandstone funcs 0
scoreboard players set scaffolding funcs 0
scoreboard players set sculk_blocks funcs 0
scoreboard players set slabs funcs 0
scoreboard players set snow funcs 0
scoreboard players set snow_blocks funcs 0
scoreboard players set soil funcs 0
scoreboard players set soul_stuff funcs 0
scoreboard players set spawner funcs 0
scoreboard players set sponge funcs 0
scoreboard players set stepable funcs 0
scoreboard players set sticky funcs 0
scoreboard players set stone funcs 0
scoreboard players set stone_bricks funcs 0
scoreboard players set structure_blocks funcs 0
scoreboard players set tnt funcs 0
scoreboard players set torches funcs 0
scoreboard players set wood_blocks funcs 0

tp @e[tag=blocks] @e[tag=death,limit=1]

execute at @e[tag=amethyst_home] run function restworld:blocks/amethyst_init
execute at @e[tag=anvil_home] run function restworld:blocks/anvil_init
execute at @e[tag=bell_home] run function restworld:blocks/bell_init
execute at @e[tag=blocks_room_home] run function restworld:blocks/blocks_room_init
execute at @e[tag=blocks_sign_home] run function restworld:blocks/blocks_sign_init
execute at @e[tag=brewing_stand_home] run function restworld:blocks/brewing_stand_init
execute at @e[tag=cake_home] run function restworld:blocks/cake_init
execute at @e[tag=campfire_home] run function restworld:blocks/campfire_init
execute at @e[tag=cauldron_home] run function restworld:blocks/cauldron_init
execute at @e[tag=chest_home] run function restworld:blocks/chest_init
execute at @e[tag=colored_beam_home] run function restworld:blocks/colored_beam_init
execute at @e[tag=colorings_home] run function restworld:blocks/colorings_init
execute at @e[tag=command_blocks_home] run function restworld:blocks/command_blocks_init
execute at @e[tag=composter_home] run function restworld:blocks/composter_init
execute at @e[tag=copper_home] run function restworld:blocks/copper_init
execute at @e[tag=dripstone_home] run function restworld:blocks/dripstone_init
execute at @e[tag=fire_home] run function restworld:blocks/fire_init
execute at @e[tag=frosted_ice_home] run function restworld:blocks/frosted_ice_init
execute at @e[tag=grindstone_home] run function restworld:blocks/grindstone_init
execute at @e[tag=item_frame_home] run function restworld:blocks/item_frame_init
execute at @e[tag=job_sites_1_home] run function restworld:blocks/job_sites_1_init
execute at @e[tag=job_sites_2_home] run function restworld:blocks/job_sites_2_init
execute at @e[tag=lantern_home] run function restworld:blocks/lantern_init
execute at @e[tag=ore_blocks_home] run function restworld:blocks/ore_blocks_init
execute at @e[tag=spawner_home] run function restworld:blocks/spawner_init
execute at @e[tag=stepable_home] run function restworld:blocks/stepable_init
execute at @e[tag=structure_blocks_home] run function restworld:blocks/structure_blocks_init
execute at @e[tag=torches_home] run function restworld:blocks/torches_init


kill @e[type=item]
