# Generated by root @ 2022-07-01 17:26:12.839006
execute positioned ~0 ~2 ~0 run kill @e[type=item_frame, tag=label, sort=nearest, distance=..2, limit=1]
summon item_frame ~0 ~2 ~0 {Facing: 1, Fixed: true, Invisible: true, Item: {Count: 1, id: stone_button, tag: {display: {Name: '{"text": "Effects Can Leave Room"}'}}}, Tags: [label]}
