# Generated by root @ 2022-07-01 17:26:12.913900
execute unless block ~-1 ~5 ~-1 acacia_wall_sign[facing=south]{Text2: '"0"'} run setblock ~-1 ~5 ~-1 acacia_wall_sign[facing=south]{Text2: '"0"'}
execute at @e[tag=font_action_home] run data modify block ~-1 ~5 ~-1 Text1 set from block ~0 ~2 ~-1 Text1
execute at @e[tag=font_action_home] run data modify block ~-1 ~5 ~-1 Text2 set from block ~0 ~2 ~-1 Text2
execute at @e[tag=font_action_home] run data modify block ~-1 ~5 ~-1 Text3 set from block ~0 ~2 ~-1 Text3
execute at @e[tag=font_action_home] run data modify block ~-1 ~5 ~-1 Text4 set from block ~0 ~2 ~-1 Text4
data modify block ~-1 ~5 ~-1 Color set from block ~0 ~-3 ~-1 Color
execute unless block ~0 ~5 ~-1 birch_wall_sign[facing=south]{Text2: '"1"'} run setblock ~0 ~5 ~-1 birch_wall_sign[facing=south]{Text2: '"1"'}
execute at @e[tag=font_action_home] run data modify block ~0 ~5 ~-1 Text1 set from block ~0 ~2 ~-1 Text1
execute at @e[tag=font_action_home] run data modify block ~0 ~5 ~-1 Text2 set from block ~0 ~2 ~-1 Text2
execute at @e[tag=font_action_home] run data modify block ~0 ~5 ~-1 Text3 set from block ~0 ~2 ~-1 Text3
execute at @e[tag=font_action_home] run data modify block ~0 ~5 ~-1 Text4 set from block ~0 ~2 ~-1 Text4
data modify block ~0 ~5 ~-1 Color set from block ~0 ~-3 ~-1 Color
execute unless block ~1 ~5 ~-1 jungle_wall_sign[facing=south]{Text2: '"2"'} run setblock ~1 ~5 ~-1 jungle_wall_sign[facing=south]{Text2: '"2"'}
execute at @e[tag=font_action_home] run data modify block ~1 ~5 ~-1 Text1 set from block ~0 ~2 ~-1 Text1
execute at @e[tag=font_action_home] run data modify block ~1 ~5 ~-1 Text2 set from block ~0 ~2 ~-1 Text2
execute at @e[tag=font_action_home] run data modify block ~1 ~5 ~-1 Text3 set from block ~0 ~2 ~-1 Text3
execute at @e[tag=font_action_home] run data modify block ~1 ~5 ~-1 Text4 set from block ~0 ~2 ~-1 Text4
data modify block ~1 ~5 ~-1 Color set from block ~0 ~-3 ~-1 Color
execute unless block ~-1 ~4 ~-1 mangrove_wall_sign[facing=south]{Text2: '"3"'} run setblock ~-1 ~4 ~-1 mangrove_wall_sign[facing=south]{Text2: '"3"'}
execute at @e[tag=font_action_home] run data modify block ~-1 ~4 ~-1 Text1 set from block ~0 ~2 ~-1 Text1
execute at @e[tag=font_action_home] run data modify block ~-1 ~4 ~-1 Text2 set from block ~0 ~2 ~-1 Text2
execute at @e[tag=font_action_home] run data modify block ~-1 ~4 ~-1 Text3 set from block ~0 ~2 ~-1 Text3
execute at @e[tag=font_action_home] run data modify block ~-1 ~4 ~-1 Text4 set from block ~0 ~2 ~-1 Text4
data modify block ~-1 ~4 ~-1 Color set from block ~0 ~-3 ~-1 Color
execute unless block ~0 ~4 ~-1 oak_wall_sign[facing=south]{Text2: '"4"'} run setblock ~0 ~4 ~-1 oak_wall_sign[facing=south]{Text2: '"4"'}
execute at @e[tag=font_action_home] run data modify block ~0 ~4 ~-1 Text1 set from block ~0 ~2 ~-1 Text1
execute at @e[tag=font_action_home] run data modify block ~0 ~4 ~-1 Text2 set from block ~0 ~2 ~-1 Text2
execute at @e[tag=font_action_home] run data modify block ~0 ~4 ~-1 Text3 set from block ~0 ~2 ~-1 Text3
execute at @e[tag=font_action_home] run data modify block ~0 ~4 ~-1 Text4 set from block ~0 ~2 ~-1 Text4
data modify block ~0 ~4 ~-1 Color set from block ~0 ~-3 ~-1 Color
execute unless block ~1 ~4 ~-1 dark_oak_wall_sign[facing=south]{Text2: '"5"'} run setblock ~1 ~4 ~-1 dark_oak_wall_sign[facing=south]{Text2: '"5"'}
execute at @e[tag=font_action_home] run data modify block ~1 ~4 ~-1 Text1 set from block ~0 ~2 ~-1 Text1
execute at @e[tag=font_action_home] run data modify block ~1 ~4 ~-1 Text2 set from block ~0 ~2 ~-1 Text2
execute at @e[tag=font_action_home] run data modify block ~1 ~4 ~-1 Text3 set from block ~0 ~2 ~-1 Text3
execute at @e[tag=font_action_home] run data modify block ~1 ~4 ~-1 Text4 set from block ~0 ~2 ~-1 Text4
data modify block ~1 ~4 ~-1 Color set from block ~0 ~-3 ~-1 Color
execute unless block ~-1 ~3 ~-1 spruce_wall_sign[facing=south]{Text2: '"6"'} run setblock ~-1 ~3 ~-1 spruce_wall_sign[facing=south]{Text2: '"6"'}
execute at @e[tag=font_action_home] run data modify block ~-1 ~3 ~-1 Text1 set from block ~0 ~2 ~-1 Text1
execute at @e[tag=font_action_home] run data modify block ~-1 ~3 ~-1 Text2 set from block ~0 ~2 ~-1 Text2
execute at @e[tag=font_action_home] run data modify block ~-1 ~3 ~-1 Text3 set from block ~0 ~2 ~-1 Text3
execute at @e[tag=font_action_home] run data modify block ~-1 ~3 ~-1 Text4 set from block ~0 ~2 ~-1 Text4
data modify block ~-1 ~3 ~-1 Color set from block ~0 ~-3 ~-1 Color
execute unless block ~0 ~3 ~-1 warped_wall_sign[facing=south]{Text2: '"7"'} run setblock ~0 ~3 ~-1 warped_wall_sign[facing=south]{Text2: '"7"'}
execute at @e[tag=font_action_home] run data modify block ~0 ~3 ~-1 Text1 set from block ~0 ~2 ~-1 Text1
execute at @e[tag=font_action_home] run data modify block ~0 ~3 ~-1 Text2 set from block ~0 ~2 ~-1 Text2
execute at @e[tag=font_action_home] run data modify block ~0 ~3 ~-1 Text3 set from block ~0 ~2 ~-1 Text3
execute at @e[tag=font_action_home] run data modify block ~0 ~3 ~-1 Text4 set from block ~0 ~2 ~-1 Text4
data modify block ~0 ~3 ~-1 Color set from block ~0 ~-3 ~-1 Color
execute unless block ~1 ~3 ~-1 crimson_wall_sign[facing=south]{Text2: '"8"'} run setblock ~1 ~3 ~-1 crimson_wall_sign[facing=south]{Text2: '"8"'}
execute at @e[tag=font_action_home] run data modify block ~1 ~3 ~-1 Text1 set from block ~0 ~2 ~-1 Text1
execute at @e[tag=font_action_home] run data modify block ~1 ~3 ~-1 Text2 set from block ~0 ~2 ~-1 Text2
execute at @e[tag=font_action_home] run data modify block ~1 ~3 ~-1 Text3 set from block ~0 ~2 ~-1 Text3
execute at @e[tag=font_action_home] run data modify block ~1 ~3 ~-1 Text4 set from block ~0 ~2 ~-1 Text4
data modify block ~1 ~3 ~-1 Color set from block ~0 ~-3 ~-1 Color
data modify block ~0 ~2 ~-1 Color set from block ~0 ~-3 ~-1 Color
data modify entity @e[tag=font, tag=nameable, limit=1] CustomName set from block ~0 ~2 ~-1 Text1
data modify entity @e[tag=font, tag=nameable, limit=1] CustomNameVisible set value true
