# Generated by root @ 2022-07-01 17:26:12.918307
kill @e[tag=font_mobs]
summon rabbit ~0 ~2 ~0 {CustomName: '"Rabbit"', NoAI: true, PersistenceRequired: true, Rotation: [0.0f, 0.0f], Silent: true, Tags: [font, nameable, rabbit, adult]}
execute as @e[tag=font, tag=nameable, limit=1] run data modify entity @s CustomNameVisible set value true
