# Generated by root @ 2022-07-01 17:26:12.642646
execute at @e[tag=all_banners_home] run function restworld:banners/all_banners_cur
execute at @e[tag=banner_color_home] run function restworld:banners/banner_color_cur
execute at @e[tag=banner_ink_home] run function restworld:banners/banner_ink_cur
