# Generated by root @ 2022-07-01 17:26:12.641293
execute at @e[tag=all_banners_home] run scoreboard players remove all_banners banners 1
execute at @e[tag=banner_color_home] run scoreboard players remove banner_color banners 1
execute at @e[tag=banner_ink_home] run scoreboard players remove banner_ink banners 1
function restworld:banners/_cur
