# Generated by root @ 2022-07-01 17:26:12.627580
setblock ~0 ~6 ~1 air
setblock ~0 ~6 ~1 oak_wall_sign[facing=south]{Text2: '{"bold": true, "italic": true, "text": "Banners &"}', Text3: '{"bold": true, "italic": true, "text": "Shields"}'}
