# Generated by root @ 2022-07-01 17:26:12.584316
summon warden ~0 ~2 ~0 {CustomName: '"Warden"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [ancient, warden, adult]}
