function restworld:ancient/_cur
function restworld:aquatic/_cur
function restworld:arena/_cur
function restworld:banners/_cur
function restworld:biomes/_cur
function restworld:blocks/_cur
function restworld:center/_cur
function restworld:connect/_cur
function restworld:containers/_cur
function restworld:diy/_cur
function restworld:effects/_cur
function restworld:enders/_cur
function restworld:font/_cur
function restworld:friendlies/_cur
function restworld:global/_cur
function restworld:materials/_cur
function restworld:monsters/_cur
function restworld:nether/_cur
function restworld:paintings/_cur
function restworld:particles/_cur
function restworld:photo/_cur
function restworld:plants/_cur
function restworld:redstone/_cur
function restworld:the_end/_cur
function restworld:time/_cur
function restworld:wither/_cur
