function restworld:ancient/_decr
function restworld:aquatic/_decr
function restworld:arena/_decr
function restworld:banners/_decr
function restworld:biomes/_decr
function restworld:blocks/_decr
function restworld:center/_decr
function restworld:connect/_decr
function restworld:containers/_decr
function restworld:diy/_decr
function restworld:effects/_decr
function restworld:enders/_decr
function restworld:font/_decr
function restworld:friendlies/_decr
function restworld:global/_decr
function restworld:materials/_decr
function restworld:monsters/_decr
function restworld:nether/_decr
function restworld:paintings/_decr
function restworld:particles/_decr
function restworld:photo/_decr
function restworld:plants/_decr
function restworld:redstone/_decr
function restworld:the_end/_decr
function restworld:time/_decr
function restworld:wither/_decr
