function restworld:ancient/_incr
function restworld:aquatic/_incr
function restworld:arena/_incr
function restworld:banners/_incr
function restworld:biomes/_incr
function restworld:blocks/_incr
function restworld:center/_incr
function restworld:connect/_incr
function restworld:containers/_incr
function restworld:diy/_incr
function restworld:effects/_incr
function restworld:enders/_incr
function restworld:font/_incr
function restworld:friendlies/_incr
function restworld:global/_incr
function restworld:materials/_incr
function restworld:monsters/_incr
function restworld:nether/_incr
function restworld:paintings/_incr
function restworld:particles/_incr
function restworld:photo/_incr
function restworld:plants/_incr
function restworld:redstone/_incr
function restworld:the_end/_incr
function restworld:time/_incr
function restworld:wither/_incr
