function restworld:ancient/_init
function restworld:aquatic/_init
function restworld:arena/_init
function restworld:banners/_init
function restworld:biomes/_init
function restworld:blocks/_init
function restworld:center/_init
function restworld:connect/_init
function restworld:containers/_init
function restworld:diy/_init
function restworld:effects/_init
function restworld:enders/_init
function restworld:font/_init
function restworld:friendlies/_init
function restworld:global/_init
function restworld:materials/_init
function restworld:monsters/_init
function restworld:nether/_init
function restworld:paintings/_init
function restworld:particles/_init
function restworld:photo/_init
function restworld:plants/_init
function restworld:redstone/_init
function restworld:the_end/_init
function restworld:time/_init
function restworld:wither/_init
