# Generated by root @ 2022-07-01 17:26:12.589432
execute at @e[tag=min_home] run fill ~0 100 ~0 ~166 100 ~180 red_concrete replace lime_concrete
execute at @e[tag=min_home] run setblock 0 105 -78 red_concrete
