# Generated by root @ 2022-07-01 17:26:12.974224
execute at @e[tag=bee_home] run scoreboard players remove bee friendlies 1
execute at @e[tag=canine_home] run scoreboard players remove canine friendlies 1
execute at @e[tag=cat_home] run scoreboard players remove cat friendlies 1
execute at @e[tag=chicken_home] run scoreboard players remove chicken friendlies 1
execute at @e[tag=colored_mobs_home] run scoreboard players remove colored_mobs friendlies 1
execute at @e[tag=cow_home] run scoreboard players remove cow friendlies 1
execute at @e[tag=fox_home] run scoreboard players remove fox friendlies 1
execute at @e[tag=frog_home] run scoreboard players remove frog friendlies 1
execute at @e[tag=frogspawn_home] run scoreboard players remove frogspawn friendlies 1
execute at @e[tag=goat_home] run scoreboard players remove goat friendlies 1
execute at @e[tag=horse_home] run scoreboard players remove horse friendlies 1
execute at @e[tag=iron_golem_home] run scoreboard players remove iron_golem friendlies 1
execute at @e[tag=llamas_carpets_home] run scoreboard players remove llamas_carpets friendlies 1
execute at @e[tag=llamas_home] run scoreboard players remove llamas friendlies 1
execute at @e[tag=panda_home] run scoreboard players remove panda friendlies 1
execute at @e[tag=parrot_home] run scoreboard players remove parrot friendlies 1
execute at @e[tag=pig_home] run scoreboard players remove pig friendlies 1
execute at @e[tag=rabbit_home] run scoreboard players remove rabbit friendlies 1
execute at @e[tag=snow_golem_home] run scoreboard players remove snow_golem friendlies 1
execute at @e[tag=trader_llama_home] run scoreboard players remove trader_llama friendlies 1
execute at @e[tag=turtle_eggs_home] run scoreboard players remove turtle_eggs friendlies 1
execute at @e[tag=villager_professions_home] run scoreboard players remove villager_professions friendlies 1
execute at @e[tag=villager_types_home] run scoreboard players remove villager_types friendlies 1
execute at @e[tag=zombie_professions_home] run scoreboard players remove zombie_professions friendlies 1
execute at @e[tag=zombie_types_home] run scoreboard players remove zombie_types friendlies 1
execute at @e[tag=villager_levels_home] run scoreboard players remove villager_levels friendlies 1
function restworld:friendlies/_cur
