# Generated by root @ 2022-07-01 17:26:12.924037
summon allay ~0 ~3 ~0 {CustomName: '"Allay"', NoAI: true, PersistenceRequired: true, Rotation: [180.0f, 0.0f], Silent: true, Tags: [a, l, l, a, y, friendlies, allay, adult]}
