# Generated by root @ 2022-07-01 17:26:12.924625
summon bat ~0 ~3 ~-2 {CustomName: '"Bat"', NoAI: true, PersistenceRequired: true, Rotation: [180.0f, 0.0f], Silent: true, Tags: [friendlies, bat, adult]}
summon bat ~0 ~3.5 ~1 {BatFlags: 1, CustomName: '"Bat"', NoAI: true, PersistenceRequired: true, Rotation: [180.0f, 0.0f], Silent: true, Tags: [friendlies, sleeping_bat, bat, adult]}
