# Generated by root @ 2022-07-01 17:26:12.930440
summon chicken ~-1.2 ~2 ~0 {CustomName: '"Chicken"', NoAI: true, PersistenceRequired: true, Rotation: [270.0f, 0.0f], Silent: true, Tags: [friendlies, chicken, adult]}
summon chicken ~1.0 ~2 ~0.0 {Age: -2147483648, CustomName: '"Chicken"', IsBaby: true, NoAI: true, PersistenceRequired: true, Rotation: [270.0f, 0.0f], Silent: true, Tags: [friendlies, chicken, kid]}
execute as @e[tag=chicken] run data merge entity @s {EggLayTime: 1000000}
