# Generated by root @ 2022-07-01 17:26:12.933891
summon fox ~-1.2 ~2 ~0 {CustomName: '"Fox"', NoAI: true, PersistenceRequired: true, Rotation: [270.0f, 0.0f], Silent: true, Tags: [friendlies, fox, adult]}
summon fox ~1.0 ~2 ~0.0 {Age: -2147483648, CustomName: '"Fox"', IsBaby: true, NoAI: true, PersistenceRequired: true, Rotation: [270.0f, 0.0f], Silent: true, Tags: [friendlies, fox, kid]}
