# Generated by root @ 2022-07-01 17:26:12.923462
setblock ~0 ~6 ~-1 air
setblock ~0 ~6 ~-1 oak_wall_sign[facing=north]{Text1: '{"bold": true, "italic": true, "text": "Villagers,"}', Text2: '{"bold": true, "italic": true, "text": "Animals,"}', Text3: '{"bold": true, "italic": true, "text": "Mobs,"}', Text4: '{"bold": true, "italic": true, "text": "Bosses"}'}
