# Generated by root @ 2022-07-01 17:26:12.936150
execute unless score frog friendlies matches 0.. run function frog_init
execute if score _to_incr friendlies matches 1.. run scoreboard players add frog friendlies 1
scoreboard players set frog friendlies_max 3
scoreboard players operation frog friendlies %= frog friendlies_max
execute if score frog friendlies matches 0 run execute as @e[tag=frog] run data merge entity @s {CustomName: '"Temperate"', variant: temperate}
execute if score frog friendlies matches 1 run execute as @e[tag=frog] run data merge entity @s {CustomName: '"Warm"', variant: warm}
execute if score frog friendlies matches 2 run execute as @e[tag=frog] run data merge entity @s {CustomName: '"Cold"', variant: cold}
