# Generated by root @ 2022-07-01 17:26:12.936751
execute unless score frogspawn friendlies matches 0.. run function frogspawn_init
execute if score _to_incr friendlies matches 1.. run scoreboard players add frogspawn friendlies 1
scoreboard players set frogspawn friendlies_max 2
scoreboard players operation frogspawn friendlies %= frogspawn friendlies_max
execute if score frogspawn friendlies matches 0 run tp @e[tag=tadpole] @e[tag=death, limit=1]
execute if score frogspawn friendlies matches 0 run setblock ~0 ~2 ~-1 frogspawn
execute if score frogspawn friendlies matches 0 run tp @e[type=tadpole, tag=!tadpole] @e[tag=death, limit=1]
execute if score frogspawn friendlies matches 1 run summon tadpole ~0 ~2 ~-1 {Age: -2147483648, CustomName: '"Tadpole"', Invulnerable: true, IsBaby: true, NoAI: true, PersistenceRequired: true, Rotation: [180.0f, 0.0f], Silent: true, Tags: [friendlies, tadpole, kid]}
execute if score frogspawn friendlies matches 1 run setblock ~0 ~2 ~-1 air
execute if score frogspawn friendlies matches 1 run tp @e[type=tadpole, tag=!tadpole] @e[tag=death, limit=1]
