# Generated by root @ 2022-07-01 17:26:12.935540
summon frog ~0 ~2 ~0.2 {CustomName: '"Frog"', NoAI: true, PersistenceRequired: true, Rotation: [180.0f, 0.0f], Silent: true, Tags: [friendlies, frog, adult]}
