# Generated by root @ 2022-07-01 17:26:12.937648
summon goat ~0 ~2 ~-0.4 {CustomName: '"Goat"', NoAI: true, PersistenceRequired: true, Rotation: [0.0f, 0.0f], Silent: true, Tags: [friendlies, goat, adult]}
summon goat ~0.0 ~2 ~2.0 {Age: -2147483648, CustomName: '"Goat"', IsBaby: true, NoAI: true, PersistenceRequired: true, Rotation: [0.0f, 0.0f], Silent: true, Tags: [friendlies, goat, kid]}
