# Generated by root @ 2022-07-01 17:26:12.941204
summon iron_golem ~-1.2 ~2 ~0 {CustomName: '"Iron Golem"', NoAI: true, PersistenceRequired: true, Rotation: [270.0f, 0.0f], Silent: true, Tags: [friendlies, iron_golem, adult]}
setblock ~2 ~2 ~0 air
setblock ~2 ~2 ~0 oak_wall_sign[facing=east]{Text2: '"Iron Golem"'}
