# Generated by root @ 2022-07-01 17:26:12.946826
summon ocelot ~0 ~2 ~-0.2 {CustomName: '"Ocelot"', NoAI: true, PersistenceRequired: true, Rotation: [0.0f, 0.0f], Silent: true, Tags: [friendlies, ocelot, adult]}
summon ocelot ~0.0 ~2 ~2.0 {Age: -2147483648, CustomName: '"Ocelot"', IsBaby: true, NoAI: true, PersistenceRequired: true, Rotation: [0.0f, 0.0f], Silent: true, Tags: [friendlies, ocelot, kid]}
