# Generated by root @ 2022-07-01 17:26:12.947417
execute as @e[tag=friendlies, tag=!homer, type=!item_frame] run data merge entity @s {Glowing: true}
execute as @e[tag=monsters, tag=!homer, type=!item_frame] run data merge entity @s {Glowing: true}
execute as @e[tag=wither, tag=!homer, type=!item_frame] run data merge entity @s {Glowing: true}
execute as @e[tag=ender, tag=!homer, type=!item_frame] run data merge entity @s {Glowing: true}
execute as @e[tag=aquatic, tag=!homer, type=!item_frame] run data merge entity @s {Glowing: true}
execute as @e[tag=ancient, tag=!homer, type=!item_frame] run data merge entity @s {Glowing: true}
