# Generated by root @ 2022-07-01 17:26:12.948002
summon panda ~0 ~2 ~-0.2 {CustomName: '"Panda"', NoAI: true, PersistenceRequired: true, Rotation: [0.0f, 0.0f], Silent: true, Tags: [friendlies, panda, adult]}
summon panda ~0.0 ~2 ~2.0 {Age: -2147483648, CustomName: '"Panda"', IsBaby: true, NoAI: true, PersistenceRequired: true, Rotation: [0.0f, 0.0f], Silent: true, Tags: [friendlies, panda, kid]}
