# Generated by root @ 2022-07-01 17:26:12.949675
summon parrot ~0 ~3 ~1 {CustomName: '"Parrot"', NoAI: true, PersistenceRequired: true, Rotation: [180.0f, 0.0f], Silent: true, Tags: [friendlies, parrot, adult]}
