# Generated by root @ 2022-07-01 17:26:12.951072
summon pig ~0.2 ~2 ~0 {CustomName: '"Pig"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [friendlies, pig, adult]}
summon pig ~-2.0 ~2 ~0.0 {Age: -2147483648, CustomName: '"Pig"', IsBaby: true, NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [friendlies, pig, kid]}
