# Generated by root @ 2022-07-01 17:26:12.952265
summon polar_bear ~0 ~2 ~-0.2 {CustomName: '"Polar Bear"', NoAI: true, PersistenceRequired: true, Rotation: [0.0f, 0.0f], Silent: true, Tags: [friendlies, polar_bear, adult]}
summon polar_bear ~0.0 ~2 ~2.0 {Age: -2147483648, CustomName: '"Polar Bear"', IsBaby: true, NoAI: true, PersistenceRequired: true, Rotation: [0.0f, 0.0f], Silent: true, Tags: [friendlies, polar_bear, kid]}
