# Generated by root @ 2022-07-01 17:26:12.952867
summon rabbit ~-1.2 ~2 ~0 {CustomName: '"Rabbit"', NoAI: true, PersistenceRequired: true, Rotation: [270.0f, 0.0f], Silent: true, Tags: [friendlies, rabbit, adult]}
summon rabbit ~1.0 ~2 ~0.0 {Age: -2147483648, CustomName: '"Rabbit"', IsBaby: true, NoAI: true, PersistenceRequired: true, Rotation: [270.0f, 0.0f], Silent: true, Tags: [friendlies, rabbit, kid]}
