# Generated by root @ 2022-07-01 17:26:12.954110
tp @e[tag=cat] @e[tag=death, limit=1]
execute at @e[tag=cat_home] run function restworld:friendlies/cat_init
execute at @e[tag=cat_home] run function restworld:friendlies/cat_cur
