# Generated by root @ 2022-07-01 17:26:12.954683
summon sheep ~0.2 ~2 ~0 {CustomName: '"Sheep"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [friendlies, colorable, sheep, adult]}
summon sheep ~-2.0 ~2 ~0.0 {Age: -2147483648, CustomName: '"Sheep"', IsBaby: true, NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [friendlies, colorable, sheep, kid]}
summon sheep ~0.2 ~2 ~2 {CustomName: '"Sheared Sheep"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Sheared: true, Silent: true, Tags: [friendlies, sheep, adult]}
summon sheep ~-2.0 ~2 ~2.0 {Age: -2147483648, CustomName: '"Sheared Sheep"', IsBaby: true, NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Sheared: true, Silent: true, Tags: [friendlies, sheep, kid]}
summon sheep ~0.2 ~2 ~4 {CustomName: '"jeb_"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [friendlies, adult]}
summon sheep ~-2.0 ~2 ~4.0 {Age: -2147483648, CustomName: '"jeb_"', IsBaby: true, NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [friendlies, kid]}
