# Generated by root @ 2022-07-01 17:26:12.955413
summon snow_golem ~-1.2 ~2 ~0 {CustomName: '"Snow Golem"', NoAI: true, PersistenceRequired: true, Rotation: [270.0f, 0.0f], Silent: true, Tags: [friendlies, snow_golem, adult]}
