# Generated by root @ 2022-07-01 17:26:12.957450
execute at @e[tag=llamas_home] positioned ~-2 ~-0.5 ~0 run function restworld:friendlies/llamas_carpets_home
execute at @e[tag=llamas_carpets_home] run function restworld:friendlies/llamas_carpets_cur
