# Generated by root @ 2022-07-01 17:26:12.958734
summon wandering_trader ~0 ~2 ~-2 {CustomName: '"Wandering Trader"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [friendlies, wandering_trader, adult]}
summon trader_llama ~0 ~2 ~0 {CustomName: '"Trader Llama"', DespawnDelay: 2147483647, Leash: {UUIDLeast: -6811205515094820418, UUIDMost: 8176443325185870163}, Leashed: true, NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [friendlies, trader_llama, adult]}
setblock ~-3 ~2 ~0 air
setblock ~-3 ~2 ~0 oak_wall_sign[facing=west]
data modify block ~-3 ~2 ~0 Text2 set value "Trader Llama"
