# Generated by root @ 2022-07-01 17:26:12.961231
summon turtle ~0 ~2 ~0.2 {CustomName: '"Turtle"', NoAI: true, PersistenceRequired: true, Rotation: [180.0f, 0.0f], Silent: true, Tags: [friendlies, turtle, adult]}
summon turtle ~0 ~2 ~-1.8 {Age: -2147483648, CustomName: '"Turtle"', IsBaby: true, NoAI: true, PersistenceRequired: true, Rotation: [180.0f, 0.0f], Silent: true, Tags: [friendlies, turtle, kid]}
