# Generated by root @ 2022-07-01 17:26:12.963480
kill @e[tag=villager]
summon villager ~-2 ~2 ~-2 {CustomName: '"Desert"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [villager, types, friendlies, villager, adult], VillagerData: {type: desert}}
summon villager ~-2 ~2 ~0 {CustomName: '"Jungle"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [villager, types, friendlies, villager, adult], VillagerData: {type: jungle}}
summon villager ~-2 ~2 ~2 {CustomName: '"Plains"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [villager, types, friendlies, villager, adult], VillagerData: {type: plains}}
summon villager ~0 ~2 ~-3 {CustomName: '"Savanna"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [villager, types, friendlies, villager, adult], VillagerData: {type: savanna}}
summon villager ~0 ~2 ~-1 {CustomName: '"Snow"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [villager, types, friendlies, villager, adult], VillagerData: {type: snow}}
summon villager ~0 ~2 ~1 {CustomName: '"Swamp"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [villager, types, friendlies, villager, adult], VillagerData: {type: swamp}}
summon villager ~0 ~2 ~3 {CustomName: '"Taiga"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [villager, types, friendlies, villager, adult], VillagerData: {type: taiga}}
function restworld:friendlies/villager_types_cur
function restworld:friendlies/villager_levels_cur
setblock ~-5 ~2 ~0 air
setblock ~-5 ~2 ~0 oak_wall_sign[facing=west]{Text3: '"Villagers"'}
