# Generated by root @ 2022-07-01 17:26:12.961838
kill @e[tag=villager]
summon villager ~-2 ~2 ~-6 {CustomName: '"Armorer"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [villager, professions, friendlies, villager, villager, adult], VillagerData: {profession: armorer}}
summon villager ~-2 ~2 ~-4 {CustomName: '"Butcher"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [villager, professions, friendlies, villager, villager, adult], VillagerData: {profession: butcher}}
summon villager ~-2 ~2 ~-2 {CustomName: '"Cartographer"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [villager, professions, friendlies, villager, villager, adult], VillagerData: {profession: cartographer}}
summon villager ~-2 ~2 ~0 {CustomName: '"Cleric"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [villager, professions, friendlies, villager, villager, adult], VillagerData: {profession: cleric}}
summon villager ~-2 ~2 ~2 {CustomName: '"Farmer"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [villager, professions, friendlies, villager, villager, adult], VillagerData: {profession: farmer}}
summon villager ~-2 ~2 ~4 {CustomName: '"Fisherman"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [villager, professions, friendlies, villager, villager, adult], VillagerData: {profession: fisherman}}
summon villager ~-2 ~2 ~6 {CustomName: '"Fletcher"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [villager, professions, friendlies, villager, villager, adult], VillagerData: {profession: fletcher}}
summon villager ~-2 ~2 ~8 {Age: -2147483648, CustomName: '"Child"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [villager, professions, friendlies, villager, adult]}
summon villager ~0 ~2 ~-7 {CustomName: '"Leatherworker"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [villager, professions, friendlies, villager, villager, adult], VillagerData: {profession: leatherworker}}
summon villager ~0 ~2 ~-5 {CustomName: '"Librarian"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [villager, professions, friendlies, villager, villager, adult], VillagerData: {profession: librarian}}
summon villager ~0 ~2 ~-3 {CustomName: '"Mason"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [villager, professions, friendlies, villager, villager, adult], VillagerData: {profession: mason}}
summon villager ~0 ~2 ~-1 {CustomName: '"Nitwit"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [villager, professions, friendlies, villager, villager, adult], VillagerData: {profession: nitwit}}
summon villager ~0 ~2 ~1 {CustomName: '"Shepherd"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [villager, professions, friendlies, villager, villager, adult], VillagerData: {profession: shepherd}}
summon villager ~0 ~2 ~3 {CustomName: '"Toolsmith"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [villager, professions, friendlies, villager, villager, adult], VillagerData: {profession: toolsmith}}
summon villager ~0 ~2 ~5 {CustomName: '"Weaponsmith"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [villager, professions, friendlies, villager, villager, adult], VillagerData: {profession: weaponsmith}}
summon villager ~0 ~2 ~7 {CustomName: '"Unemployed"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [villager, professions, friendlies, villager, villager, adult], VillagerData: {profession: unemployed}}
function restworld:friendlies/villager_professions_cur
function restworld:friendlies/villager_levels_cur
setblock ~-5 ~2 ~0 air
setblock ~-5 ~2 ~0 oak_wall_sign[facing=west]{Text3: '"Villager"'}
