# Generated by root @ 2022-07-01 17:26:12.626932
execute at @e[tag=arena_count_home] run function restworld:arena/arena_count_cur
execute at @e[tag=arena_run_home] run function restworld:arena/arena_run_cur
execute at @e[tag=toggle_peace_home] run function restworld:arena/toggle_peace_cur
