# Generated by root @ 2022-07-01 17:26:12.624314
execute at @e[tag=arena_count_home] run function restworld:arena/arena_count_main
execute at @e[tag=arena_run_home] run function restworld:arena/arena_run_main
