# Generated by root @ 2022-07-01 17:26:12.620143
kill @e[tag=hunter_home]
summon armor_stand ~-1 ~-0.5 ~-1 {NoGravity: true, Small: true, Tags: [hunter_home, home, arena_home]}
summon armor_stand ~-1 ~-0.5 ~0 {NoGravity: true, Small: true, Tags: [hunter_home, home, arena_home]}
summon armor_stand ~-1 ~-0.5 ~1 {NoGravity: true, Small: true, Tags: [hunter_home, home, arena_home]}
summon armor_stand ~0 ~-0.5 ~-1 {NoGravity: true, Small: true, Tags: [hunter_home, home, arena_home]}
summon armor_stand ~0 ~-0.5 ~0 {NoGravity: true, Small: true, Tags: [hunter_home, home, arena_home]}
summon armor_stand ~0 ~-0.5 ~1 {NoGravity: true, Small: true, Tags: [hunter_home, home, arena_home]}
summon armor_stand ~1 ~-0.5 ~-1 {NoGravity: true, Small: true, Tags: [hunter_home, home, arena_home]}
summon armor_stand ~1 ~-0.5 ~0 {NoGravity: true, Small: true, Tags: [hunter_home, home, arena_home]}
summon armor_stand ~1 ~-0.5 ~1 {NoGravity: true, Small: true, Tags: [hunter_home, home, arena_home]}
