# Generated by root @ 2022-07-01 17:26:12.580858
function restworld:ancient/_cur
function restworld:global/_cur
function restworld:aquatic/_cur
function restworld:arena/_cur
function restworld:banners/_cur
function restworld:biomes/_cur
function restworld:blocks/_cur
function restworld:center/_cur
function restworld:containers/_cur
function restworld:diy/_cur
function restworld:effects/_cur
function restworld:particles/_cur
function restworld:enders/_cur
function restworld:font/_cur
function restworld:friendlies/_cur
function restworld:materials/_cur
