# Generated by root @ 2022-07-01 17:26:12.580551
function restworld:ancient/_decr
function restworld:global/_decr
function restworld:aquatic/_decr
function restworld:arena/_decr
function restworld:banners/_decr
function restworld:biomes/_decr
function restworld:blocks/_decr
function restworld:center/_decr
function restworld:containers/_decr
function restworld:diy/_decr
function restworld:effects/_decr
function restworld:particles/_decr
function restworld:enders/_decr
function restworld:font/_decr
function restworld:friendlies/_decr
function restworld:materials/_decr
