# Generated by root @ 2022-07-01 17:26:12.579927
function restworld:ancient/_enter
function restworld:global/_enter
function restworld:aquatic/_enter
function restworld:arena/_enter
function restworld:banners/_enter
function restworld:biomes/_enter
function restworld:blocks/_enter
function restworld:center/_enter
function restworld:containers/_enter
function restworld:diy/_enter
function restworld:effects/_enter
function restworld:particles/_enter
function restworld:enders/_enter
function restworld:font/_enter
function restworld:friendlies/_enter
function restworld:materials/_enter
