# Generated by root @ 2022-07-01 17:26:12.581170
function restworld:ancient/_exit
function restworld:global/_exit
function restworld:aquatic/_exit
function restworld:arena/_exit
function restworld:banners/_exit
function restworld:biomes/_exit
function restworld:blocks/_exit
function restworld:center/_exit
function restworld:containers/_exit
function restworld:diy/_exit
function restworld:effects/_exit
function restworld:particles/_exit
function restworld:enders/_exit
function restworld:font/_exit
function restworld:friendlies/_exit
function restworld:materials/_exit
