# Generated by root @ 2022-07-01 17:26:12.580239
function restworld:ancient/_incr
function restworld:global/_incr
function restworld:aquatic/_incr
function restworld:arena/_incr
function restworld:banners/_incr
function restworld:biomes/_incr
function restworld:blocks/_incr
function restworld:center/_incr
function restworld:containers/_incr
function restworld:diy/_incr
function restworld:effects/_incr
function restworld:particles/_incr
function restworld:enders/_incr
function restworld:font/_incr
function restworld:friendlies/_incr
function restworld:materials/_incr
