# Generated by root @ 2022-07-01 17:26:12.579587
function restworld:ancient/_init
function restworld:global/_init
function restworld:aquatic/_init
function restworld:arena/_init
function restworld:banners/_init
function restworld:biomes/_init
function restworld:blocks/_init
function restworld:center/_init
function restworld:containers/_init
function restworld:diy/_init
function restworld:effects/_init
function restworld:particles/_init
function restworld:enders/_init
function restworld:font/_init
function restworld:friendlies/_init
function restworld:materials/_init
