# Generated by root @ 2022-07-01 17:26:12.581799
function restworld:ancient/_slow
function restworld:global/_slow
function restworld:aquatic/_slow
function restworld:arena/_slow
function restworld:banners/_slow
function restworld:biomes/_slow
function restworld:blocks/_slow
function restworld:center/_slow
function restworld:containers/_slow
function restworld:diy/_slow
function restworld:effects/_slow
function restworld:particles/_slow
function restworld:enders/_slow
function restworld:font/_slow
function restworld:friendlies/_slow
function restworld:materials/_slow
