# Generated by root @ 2022-07-01 17:26:12.579120
function restworld:ancient/_tick
function restworld:global/_tick
function restworld:aquatic/_tick
function restworld:arena/_tick
function restworld:banners/_tick
function restworld:biomes/_tick
function restworld:blocks/_tick
function restworld:center/_tick
function restworld:containers/_tick
function restworld:diy/_tick
function restworld:effects/_tick
function restworld:particles/_tick
function restworld:enders/_tick
function restworld:font/_tick
function restworld:friendlies/_tick
function restworld:materials/_tick
