# Generated by root @ 2022-07-01 17:26:12.910972
execute at @e[tag=cage_home] run function restworld:enders/cage_cur
execute at @e[tag=crystal_home] run function restworld:enders/crystal_cur
execute at @e[tag=dragon_head_home] run function restworld:enders/dragon_head_cur
execute at @e[tag=end_portal_home] run function restworld:enders/end_portal_cur
execute at @e[tag=shulker_color_home] run function restworld:enders/shulker_color_cur
execute at @e[tag=shulker_home] run function restworld:enders/shulker_cur
