# Generated by root @ 2022-07-01 17:26:12.904803
summon endermite ~0 ~2 ~-0.2 {CustomName: '"Endermite"', NoAI: true, PersistenceRequired: true, Rotation: [180.0f, 0.0f], Silent: true, Tags: [enders, endermite, adult]}
