# Generated by root @ 2022-07-01 17:26:12.903718
execute unless entity @e[type=enderman, distance=..5] run summon enderman ~0 ~2 ~0 {CustomName: '"Enderman"', NoAI: true, PersistenceRequired: true, Rotation: [180.0f, 0.0f], Silent: true, Tags: [enders, enderman, adult]}
