# Generated by root @ 2022-07-01 17:26:12.905766
execute unless score shulker_color enders matches 0.. run function shulker_color_init
execute if score _to_incr enders matches 1.. run scoreboard players add shulker_color enders 1
scoreboard players set shulker_color enders_max 16
scoreboard players operation shulker_color enders %= shulker_color enders_max
execute if score shulker_color enders matches 0 run data merge entity @e[tag=shulker, limit=1] {Color: 0}
execute if score shulker_color enders matches 1 run data merge entity @e[tag=shulker, limit=1] {Color: 1}
execute if score shulker_color enders matches 2 run data merge entity @e[tag=shulker, limit=1] {Color: 2}
execute if score shulker_color enders matches 3 run data merge entity @e[tag=shulker, limit=1] {Color: 3}
execute if score shulker_color enders matches 4 run data merge entity @e[tag=shulker, limit=1] {Color: 4}
execute if score shulker_color enders matches 5 run data merge entity @e[tag=shulker, limit=1] {Color: 5}
execute if score shulker_color enders matches 6 run data merge entity @e[tag=shulker, limit=1] {Color: 6}
execute if score shulker_color enders matches 7 run data merge entity @e[tag=shulker, limit=1] {Color: 7}
execute if score shulker_color enders matches 8 run data merge entity @e[tag=shulker, limit=1] {Color: 8}
execute if score shulker_color enders matches 9 run data merge entity @e[tag=shulker, limit=1] {Color: 9}
execute if score shulker_color enders matches 10 run data merge entity @e[tag=shulker, limit=1] {Color: 10}
execute if score shulker_color enders matches 11 run data merge entity @e[tag=shulker, limit=1] {Color: 11}
execute if score shulker_color enders matches 12 run data merge entity @e[tag=shulker, limit=1] {Color: 12}
execute if score shulker_color enders matches 13 run data merge entity @e[tag=shulker, limit=1] {Color: 13}
execute if score shulker_color enders matches 14 run data merge entity @e[tag=shulker, limit=1] {Color: 14}
execute if score shulker_color enders matches 15 run data merge entity @e[tag=shulker, limit=1] {Color: 15}
