scoreboard players set ambient funcs 0
scoreboard players set angry_villager funcs 0
scoreboard players set ash funcs 0
scoreboard players set bubbles funcs 0
scoreboard players set composter funcs 0
scoreboard players set crimson_spore funcs 0
scoreboard players set crit funcs 0
scoreboard players set damage_indicator funcs 0
scoreboard players set dolphin funcs 0
scoreboard players set dragon_breath funcs 0
scoreboard players set dripping_honey funcs 0
scoreboard players set dripping_lava funcs 0
scoreboard players set dripping_obsidian_tear funcs 0
scoreboard players set dripping_water funcs 0
scoreboard players set dust funcs 0
scoreboard players set effect funcs 0
scoreboard players set electric_spark funcs 0
scoreboard players set enchant funcs 0
scoreboard players set enchanted_hit funcs 0
scoreboard players set end_rod funcs 0
scoreboard players set entity_effect funcs 0
scoreboard players set falling_dust funcs 0
scoreboard players set falling_nectar funcs 0
scoreboard players set fireworks funcs 0
scoreboard players set fishing funcs 0
scoreboard players set flame funcs 0
scoreboard players set happy_villager funcs 0
scoreboard players set heart funcs 0
scoreboard players set instant_effect funcs 0
scoreboard players set item_slime funcs 0
scoreboard players set item_snowball funcs 0
scoreboard players set large_smoke funcs 0
scoreboard players set lava funcs 0
scoreboard players set mycelium funcs 0
scoreboard players set nautilus funcs 0
scoreboard players set note funcs 0
scoreboard players set particles_room funcs 0
scoreboard players set portal funcs 0
scoreboard players set sculk_sensor funcs 0
scoreboard players set sculk_soul funcs 0
scoreboard players set shriek funcs 0
scoreboard players set smoke funcs 0
scoreboard players set sneeze funcs 0
scoreboard players set snow_and_rain funcs 0
scoreboard players set soul funcs 0
scoreboard players set spit funcs 0
scoreboard players set splash funcs 0
scoreboard players set spore_blossom funcs 0
scoreboard players set squid_ink funcs 0
scoreboard players set underwater funcs 0
scoreboard players set warped_spore funcs 0
scoreboard players set wax funcs 0
scoreboard players set white_ash funcs 0
scoreboard players set witch funcs 0

tp @e[tag=particles] @e[tag=death,limit=1]

execute at @e[tag=ambient_home] run function restworld:particles/ambient_init
execute at @e[tag=angry_villager_home] run function restworld:particles/angry_villager_init
execute at @e[tag=ash_home] run function restworld:particles/ash_init
execute at @e[tag=bubbles_home] run function restworld:particles/bubbles_init
execute at @e[tag=composter_home] run function restworld:particles/composter_init
execute at @e[tag=crimson_spore_home] run function restworld:particles/crimson_spore_init
execute at @e[tag=crit_home] run function restworld:particles/crit_init
execute at @e[tag=damage_indicator_home] run function restworld:particles/damage_indicator_init
execute at @e[tag=dolphin_home] run function restworld:particles/dolphin_init
execute at @e[tag=dragon_breath_home] run function restworld:particles/dragon_breath_init
execute at @e[tag=dripping_honey_home] run function restworld:particles/dripping_honey_init
execute at @e[tag=dripping_lava_home] run function restworld:particles/dripping_lava_init
execute at @e[tag=dripping_obsidian_tear_home] run function restworld:particles/dripping_obsidian_tear_init
execute at @e[tag=dripping_water_home] run function restworld:particles/dripping_water_init
execute at @e[tag=dust_home] run function restworld:particles/dust_init
execute at @e[tag=effect_home] run function restworld:particles/effect_init
execute at @e[tag=electric_spark_home] run function restworld:particles/electric_spark_init
execute at @e[tag=enchant_home] run function restworld:particles/enchant_init
execute at @e[tag=enchanted_hit_home] run function restworld:particles/enchanted_hit_init
execute at @e[tag=end_rod_home] run function restworld:particles/end_rod_init
execute at @e[tag=entity_effect_home] run function restworld:particles/entity_effect_init
execute at @e[tag=falling_dust_home] run function restworld:particles/falling_dust_init
execute at @e[tag=falling_nectar_home] run function restworld:particles/falling_nectar_init
execute at @e[tag=fireworks_home] run function restworld:particles/fireworks_init
execute at @e[tag=fishing_home] run function restworld:particles/fishing_init
execute at @e[tag=flame_home] run function restworld:particles/flame_init
execute at @e[tag=happy_villager_home] run function restworld:particles/happy_villager_init
execute at @e[tag=heart_home] run function restworld:particles/heart_init
execute at @e[tag=instant_effect_home] run function restworld:particles/instant_effect_init
execute at @e[tag=item_slime_home] run function restworld:particles/item_slime_init
execute at @e[tag=item_snowball_home] run function restworld:particles/item_snowball_init
execute at @e[tag=large_smoke_home] run function restworld:particles/large_smoke_init
execute at @e[tag=lava_home] run function restworld:particles/lava_init
execute at @e[tag=mycelium_home] run function restworld:particles/mycelium_init
execute at @e[tag=nautilus_home] run function restworld:particles/nautilus_init
execute at @e[tag=note_home] run function restworld:particles/note_init
execute at @e[tag=particles_room_home] run function restworld:particles/particles_room_init
execute at @e[tag=portal_home] run function restworld:particles/portal_init
execute at @e[tag=sculk_sensor_home] run function restworld:particles/sculk_sensor_init
execute at @e[tag=sculk_soul_home] run function restworld:particles/sculk_soul_init
execute at @e[tag=shriek_home] run function restworld:particles/shriek_init
execute at @e[tag=smoke_home] run function restworld:particles/smoke_init
execute at @e[tag=sneeze_home] run function restworld:particles/sneeze_init
execute at @e[tag=snow_and_rain_home] run function restworld:particles/snow_and_rain_init
execute at @e[tag=soul_home] run function restworld:particles/soul_init
execute at @e[tag=spit_home] run function restworld:particles/spit_init
execute at @e[tag=splash_home] run function restworld:particles/splash_init
execute at @e[tag=spore_blossom_home] run function restworld:particles/spore_blossom_init
execute at @e[tag=squid_ink_home] run function restworld:particles/squid_ink_init
execute at @e[tag=underwater_home] run function restworld:particles/underwater_init
execute at @e[tag=warped_spore_home] run function restworld:particles/warped_spore_init
execute at @e[tag=wax_home] run function restworld:particles/wax_init
execute at @e[tag=white_ash_home] run function restworld:particles/white_ash_init
execute at @e[tag=witch_home] run function restworld:particles/witch_init


kill @e[type=item]
