# Generated by root @ 2022-07-01 17:26:12.614674
execute at @e[tag=2_fish_home] run function restworld:aquatic/2_fish_cur
execute at @e[tag=3_fish_home] run function restworld:aquatic/3_fish_cur
execute at @e[tag=all_fish_home] run function restworld:aquatic/all_fish_cur
execute at @e[tag=axolotl_home] run function restworld:aquatic/axolotl_cur
execute at @e[tag=fishies_home] run function restworld:aquatic/fishies_cur
execute at @e[tag=squid_home] run function restworld:aquatic/squid_cur
