# Generated by root @ 2022-07-01 17:26:12.613437
execute at @e[tag=2_fish_home] run scoreboard players add 2_fish aquatic 1
execute at @e[tag=3_fish_home] run scoreboard players add 3_fish aquatic 1
execute at @e[tag=all_fish_home] run scoreboard players add all_fish aquatic 1
execute at @e[tag=axolotl_home] run scoreboard players add axolotl aquatic 1
execute at @e[tag=fishies_home] run scoreboard players add fishies aquatic 1
execute at @e[tag=squid_home] run scoreboard players add squid aquatic 1
function restworld:aquatic/_cur
