# Generated by root @ 2022-07-01 17:26:12.612293
execute if score main clocks matches 0 run function restworld:aquatic/_main
execute if score fast clocks matches 0 run function restworld:aquatic/_fast
