# Generated by root @ 2022-07-01 17:26:12.607040
summon axolotl ~1.3 ~4 ~1.3 {CustomName: '"Axolotl"', NoAI: true, PersistenceRequired: true, Rotation: [135.0f, 0.0f], Silent: true, Tags: [aquatic, axolotl, adult]}
summon axolotl ~-0.1 ~4 ~-0.1 {Age: -2147483648, CustomName: '"Axolotl"', IsBaby: true, NoAI: true, PersistenceRequired: true, Rotation: [135.0f, 0.0f], Silent: true, Tags: [aquatic, axolotl, kid]}
