# Generated by root @ 2022-07-01 17:26:12.608332
summon elder_guardian ~2 ~3 ~0 {CustomName: '"Elder Guardian"', NoAI: true, PersistenceRequired: true, Rotation: [225.0f, 0.0f], Silent: true, Tags: [aquatic, elder_guardian, adult]}
