# Generated by root @ 2022-07-01 17:26:12.609498
summon dolphin ~1.8 ~4 ~0 {CustomName: '"Dolphin"', Invulnerable: true, NoAI: true, PersistenceRequired: true, Rotation: [270.0f, 0.0f], Silent: true, Tags: [aquatic, dolphin, adult]}
summon salmon ~1.8 ~4 ~-4 {CustomName: '"Salmon"', NoAI: true, PersistenceRequired: true, Rotation: [270.0f, 0.0f], Silent: true, Tags: [aquatic, salmon, adult]}
summon cod ~1.8 ~4 ~-5 {CustomName: '"Cod"', NoAI: true, PersistenceRequired: true, Rotation: [270.0f, 0.0f], Silent: true, Tags: [aquatic, cod, adult]}
summon pufferfish ~1.8 ~4 ~-6 {CustomName: '"Pufferfish"', NoAI: true, PersistenceRequired: true, Rotation: [270.0f, 0.0f], Silent: true, Tags: [aquatic, pufferfish, adult]}
summon tadpole ~1.8 ~4 ~-7 {Age: -2147483648, CustomName: '"Tadpole"', Invulnerable: true, NoAI: true, PersistenceRequired: true, Rotation: [270.0f, 0.0f], Silent: true, Tags: [kid, aquatic, tadpole, adult]}
