# Generated by root @ 2022-07-01 17:26:12.608918
summon guardian ~-0.6 ~3 ~0 {CustomName: '"Guardian"', NoAI: true, PersistenceRequired: true, Rotation: [180.0f, 0.0f], Silent: true, Tags: [aquatic, guardian, adult]}
