# Generated by root @ 2022-07-01 17:26:12.606312
summon tropical_fish ~0.5 ~3.2 ~0 {CustomName: '"Tropical Fish"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [kob, aquatic, tropical_fish, adult], Variant: 917504}
summon tropical_fish ~0.5 ~3.2 ~1 {CustomName: '"Tropical Fish"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [sunstreak, aquatic, tropical_fish, adult], Variant: 134217984}
summon tropical_fish ~0.5 ~3.2 ~2 {CustomName: '"Tropical Fish"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [gray_red_snooper, aquatic, tropical_fish, adult], Variant: 235340288}
summon tropical_fish ~0.5 ~3.2 ~3 {CustomName: '"Tropical Fish"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [dasher, aquatic, tropical_fish, adult], Variant: 117441280}
summon tropical_fish ~0.5 ~3.2 ~4 {CustomName: '"Tropical Fish"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [brinely, aquatic, tropical_fish, adult], Variant: 117441536}
summon tropical_fish ~0.5 ~3.2 ~5 {CustomName: '"Tropical Fish"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [spotty, aquatic, tropical_fish, adult], Variant: 67110144}
summon tropical_fish ~1.5 ~3.2 ~0 {CustomName: '"Tropical Fish"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [flopper, aquatic, tropical_fish, adult], Variant: 117899265}
summon tropical_fish ~1.5 ~3.2 ~1 {CustomName: '"Tropical Fish"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [stripey, aquatic, tropical_fish, adult], Variant: 117506305}
summon tropical_fish ~1.5 ~3.2 ~2 {CustomName: '"Tropical Fish"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [white_gray_glitter, aquatic, tropical_fish, adult], Variant: 117441025}
summon tropical_fish ~1.5 ~3.2 ~3 {CustomName: '"Tropical Fish"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [blockfish, aquatic, tropical_fish, adult], Variant: 67764993}
summon tropical_fish ~1.5 ~3.2 ~4 {CustomName: '"Tropical Fish"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [red_white_betty, aquatic, tropical_fish, adult], Variant: 918529}
summon tropical_fish ~1.5 ~3.2 ~5 {CustomName: '"Tropical Fish"', NoAI: true, PersistenceRequired: true, Rotation: [90.0f, 0.0f], Silent: true, Tags: [clayfish, aquatic, tropical_fish, adult], Variant: 234882305}
setblock ~0 ~2 ~5 water
setblock ~0 ~2 ~5 oak_wall_sign[facing=west, waterlogged=true]{Text1: '"Naturally"', Text2: '"Occurring"', Text3: '"Tropical Fish"', Text4: '"<--------"'}
