execute unless score arena_run_type funcs matches 0.. run scoreboard players set arena_run_type funcs 0




fill ~-2 ~2 ~-2 ~-2 ~3 ~2 air


scoreboard players set arena_run max 5
execute unless score arena_run funcs matches 0..4 run scoreboard players operation arena_run funcs %= arena_run max
execute if score arena_run funcs matches 0 run setblock ~-2 ~2 ~2 oak_wall_sign[facing=east]{GlowingText:True,Text2:"{\"text\":\"<--\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_action_home] positioned ~0 ~2 ~0 run scoreboard players set arena_run funcs 4\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=controls_home] run function restworld:arena/arena_run_cur\"}}"}
execute if score arena_run funcs matches 0 run setblock ~-2 ~2 ~-2 oak_wall_sign[facing=east]{GlowingText:True,Text2:"{\"text\":\"-->\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_action_home] positioned ~0 ~2 ~0 run scoreboard players set arena_run funcs 1\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=controls_home] run function restworld:arena/arena_run_cur\"}}"}


execute if score arena_run funcs matches 0 run setblock ~-2 ~3 ~1.0 air
execute if score arena_run funcs matches 0 run setblock ~-2 ~3 ~1.0 oak_wall_sign[facing=east]{    Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run scoreboard players set start_battle_type funcs 1\"}}",    Text2:"{\"text\":\"Axolotl\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~2 ~0 ~0 {Command:\\\"execute if score hunter_count funcs < arena_count funcs at @e[tag=hunter_home,sort=random,limit=1] run summon axolotl ~0 ~2 ~0 {Tags:[battler,hunter],Rotation:[180f,0f]}\\\"}\"}}",    Text3:"{\"text\":\"vs.\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~3 ~0 ~0 {Command:\\\"execute if score victim_count funcs < arena_count funcs at @e[tag=victim_home,sort=random,limit=1] run summon drowned ~0 ~2 ~0 {Tags:[battler,victim],HandItems:[{id:trident,Count:1}]}\\\"}\"}}",    Text4:"{\"text\":\"Drowned\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run function restworld:arena/start_battle\"}}"}



execute if score arena_run funcs matches 0 run setblock ~-2 ~3 ~0.0 air
execute if score arena_run funcs matches 0 run setblock ~-2 ~3 ~0.0 oak_wall_sign[facing=east]{    Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run scoreboard players set start_battle_type funcs 0\"}}",    Text2:"{\"text\":\"Blaze\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~2 ~0 ~0 {Command:\\\"execute if score hunter_count funcs < arena_count funcs at @e[tag=hunter_home,sort=random,limit=1] run summon blaze ~0 ~2 ~0 {Tags:[battler,hunter],Rotation:[180f,0f]}\\\"}\"}}",    Text3:"{\"text\":\"vs.\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~3 ~0 ~0 {Command:\\\"execute if score victim_count funcs < arena_count funcs at @e[tag=victim_home,sort=random,limit=1] run summon snow_golem ~0 ~2 ~0 {Tags:[battler,victim]}\\\"}\"}}",    Text4:"{\"text\":\"Snow Golem\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run function restworld:arena/start_battle\"}}"}



execute if score arena_run funcs matches 0 run setblock ~-2 ~3 ~-1.0 air
execute if score arena_run funcs matches 0 run setblock ~-2 ~3 ~-1.0 oak_wall_sign[facing=east]{    Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run scoreboard players set start_battle_type funcs 0\"}}",    Text2:"{\"text\":\"Cat\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~2 ~0 ~0 {Command:\\\"execute if score hunter_count funcs < arena_count funcs at @e[tag=hunter_home,sort=random,limit=1] run summon cat ~0 ~2 ~0 {Tags:[battler,hunter],Rotation:[180f,0f]}\\\"}\"}}",    Text3:"{\"text\":\"vs.\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~3 ~0 ~0 {Command:\\\"execute if score victim_count funcs < arena_count funcs at @e[tag=victim_home,sort=random,limit=1] run summon rabbit ~0 ~2 ~0 {Tags:[battler,victim]}\\\"}\"}}",    Text4:"{\"text\":\"Rabbit\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run function restworld:arena/start_battle\"}}"}



execute if score arena_run funcs matches 0 run setblock ~-2 ~2 ~1.0 air
execute if score arena_run funcs matches 0 run setblock ~-2 ~2 ~1.0 oak_wall_sign[facing=east]{    Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run scoreboard players set start_battle_type funcs 0\"}}",    Text2:"{\"text\":\"Cave Spider\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~2 ~0 ~0 {Command:\\\"execute if score hunter_count funcs < arena_count funcs at @e[tag=hunter_home,sort=random,limit=1] run summon cave_spider ~0 ~2 ~0 {Tags:[battler,hunter],Rotation:[180f,0f]}\\\"}\"}}",    Text3:"{\"text\":\"vs.\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~3 ~0 ~0 {Command:\\\"execute if score victim_count funcs < arena_count funcs at @e[tag=victim_home,sort=random,limit=1] run summon snow_golem ~0 ~2 ~0 {Tags:[battler,victim]}\\\"}\"}}",    Text4:"{\"text\":\"Snow Golem\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run function restworld:arena/start_battle\"}}"}



execute if score arena_run funcs matches 0 run setblock ~-2 ~2 ~0.0 air
execute if score arena_run funcs matches 0 run setblock ~-2 ~2 ~0.0 oak_wall_sign[facing=east]{    Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run scoreboard players set start_battle_type funcs 2\"}}",    Text2:"{\"text\":\"Drowned\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~2 ~0 ~0 {Command:\\\"execute if score hunter_count funcs < arena_count funcs at @e[tag=hunter_home,sort=random,limit=1] run summon drowned ~0 ~2 ~0 {Tags:[battler,hunter],HandItems:[{id:trident,Count:1}],Rotation:[180f,0f]}\\\"}\"}}",    Text3:"{\"text\":\"vs.\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~3 ~0 ~0 {Command:\\\"execute if score victim_count funcs < arena_count funcs at @e[tag=victim_home,sort=random,limit=1] run summon snow_golem ~0 ~2 ~0 {Tags:[battler,victim]}\\\"}\"}}",    Text4:"{\"text\":\"Snow Golem\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run function restworld:arena/start_battle\"}}"}



execute if score arena_run funcs matches 0 run setblock ~-2 ~2 ~-1.0 air
execute if score arena_run funcs matches 0 run setblock ~-2 ~2 ~-1.0 oak_wall_sign[facing=east]{    Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run scoreboard players set start_battle_type funcs 0\"}}",    Text2:"{\"text\":\"Evoker\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~2 ~0 ~0 {Command:\\\"execute if score hunter_count funcs < arena_count funcs at @e[tag=hunter_home,sort=random,limit=1] run summon evoker ~0 ~2 ~0 {Tags:[battler,hunter],Rotation:[180f,0f]}\\\"}\"}}",    Text3:"{\"text\":\"vs.\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~3 ~0 ~0 {Command:\\\"execute if score victim_count funcs < arena_count funcs at @e[tag=victim_home,sort=random,limit=1] run summon iron_golem ~0 ~2 ~0 {Tags:[battler,victim]}\\\"}\"}}",    Text4:"{\"text\":\"Iron Golem\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run function restworld:arena/start_battle\"}}"}


execute if score arena_run funcs matches 1 run setblock ~-2 ~2 ~2 oak_wall_sign[facing=east]{GlowingText:True,Text2:"{\"text\":\"<--\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_action_home] positioned ~0 ~2 ~0 run scoreboard players set arena_run funcs 0\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=controls_home] run function restworld:arena/arena_run_cur\"}}"}
execute if score arena_run funcs matches 1 run setblock ~-2 ~2 ~-2 oak_wall_sign[facing=east]{GlowingText:True,Text2:"{\"text\":\"-->\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_action_home] positioned ~0 ~2 ~0 run scoreboard players set arena_run funcs 2\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=controls_home] run function restworld:arena/arena_run_cur\"}}"}


execute if score arena_run funcs matches 1 run setblock ~-2 ~3 ~1.0 air
execute if score arena_run funcs matches 1 run setblock ~-2 ~3 ~1.0 oak_wall_sign[facing=east]{    Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run scoreboard players set start_battle_type funcs 0\"}}",    Text2:"{\"text\":\"Fox\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~2 ~0 ~0 {Command:\\\"execute if score hunter_count funcs < arena_count funcs at @e[tag=hunter_home,sort=random,limit=1] run summon fox ~0 ~2 ~0 {Tags:[battler,hunter],Rotation:[180f,0f]}\\\"}\"}}",    Text3:"{\"text\":\"vs.\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~3 ~0 ~0 {Command:\\\"execute if score victim_count funcs < arena_count funcs at @e[tag=victim_home,sort=random,limit=1] run summon chicken ~0 ~2 ~0 {Tags:[battler,victim]}\\\"}\"}}",    Text4:"{\"text\":\"Chicken\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run function restworld:arena/start_battle\"}}"}



execute if score arena_run funcs matches 1 run setblock ~-2 ~3 ~0.0 air
execute if score arena_run funcs matches 1 run setblock ~-2 ~3 ~0.0 oak_wall_sign[facing=east]{    Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run scoreboard players set start_battle_type funcs 0\"}}",    Text2:"{\"text\":\"Frog\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~2 ~0 ~0 {Command:\\\"execute if score hunter_count funcs < arena_count funcs at @e[tag=hunter_home,sort=random,limit=1] run summon frog ~0 ~2 ~0 {Tags:[battler,hunter],Rotation:[180f,0f]}\\\"}\"}}",    Text3:"{\"text\":\"vs.\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~3 ~0 ~0 {Command:\\\"execute if score victim_count funcs < arena_count funcs at @e[tag=victim_home,sort=random,limit=1] run summon slime ~0 ~2 ~0 {Tags:[battler,victim],Size:0}\\\"}\"}}",    Text4:"{\"text\":\"Slime\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run function restworld:arena/start_battle\"}}"}



execute if score arena_run funcs matches 1 run setblock ~-2 ~3 ~-1.0 air
execute if score arena_run funcs matches 1 run setblock ~-2 ~3 ~-1.0 oak_wall_sign[facing=east]{    Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run scoreboard players set start_battle_type funcs 0\"}}",    Text2:"{\"text\":\"Goat\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~2 ~0 ~0 {Command:\\\"execute if score hunter_count funcs < arena_count funcs at @e[tag=hunter_home,sort=random,limit=1] run summon goat ~0 ~2 ~0 {Tags:[battler,hunter],IsScreamingGoat:True,Rotation:[180f,0f]}\\\"}\"}}",    Text3:"{\"text\":\"vs.\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~3 ~0 ~0 {Command:\\\"execute if score victim_count funcs < arena_count funcs at @e[tag=victim_home,sort=random,limit=1] run summon sheep ~0 ~2 ~0 {Tags:[battler,victim]}\\\"}\"}}",    Text4:"{\"text\":\"Sheep\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run function restworld:arena/start_battle\"}}"}



execute if score arena_run funcs matches 1 run setblock ~-2 ~2 ~1.0 air
execute if score arena_run funcs matches 1 run setblock ~-2 ~2 ~1.0 oak_wall_sign[facing=east]{    Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run scoreboard players set start_battle_type funcs 0\"}}",    Text2:"{\"text\":\"Hoglin\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~2 ~0 ~0 {Command:\\\"execute if score hunter_count funcs < arena_count funcs at @e[tag=hunter_home,sort=random,limit=1] run summon hoglin ~0 ~2 ~0 {Tags:[battler,hunter],IsImmuneToZombification:True,Rotation:[180f,0f]}\\\"}\"}}",    Text3:"{\"text\":\"vs.\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~3 ~0 ~0 {Command:\\\"execute if score victim_count funcs < arena_count funcs at @e[tag=victim_home,sort=random,limit=1] run summon vindicator ~0 ~2 ~0 {Tags:[battler,victim],Johnny:True,HandItems:[{id:iron_axe,Count:1},{}]}\\\"}\"}}",    Text4:"{\"text\":\"Vindicator\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run function restworld:arena/start_battle\"}}"}



execute if score arena_run funcs matches 1 run setblock ~-2 ~2 ~0.0 air
execute if score arena_run funcs matches 1 run setblock ~-2 ~2 ~0.0 oak_wall_sign[facing=east]{    Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run scoreboard players set start_battle_type funcs 0\"}}",    Text2:"{\"text\":\"Illusioner\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~2 ~0 ~0 {Command:\\\"execute if score hunter_count funcs < arena_count funcs at @e[tag=hunter_home,sort=random,limit=1] run summon illusioner ~0 ~2 ~0 {Tags:[battler,hunter],Rotation:[180f,0f]}\\\"}\"}}",    Text3:"{\"text\":\"vs.\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~3 ~0 ~0 {Command:\\\"execute if score victim_count funcs < arena_count funcs at @e[tag=victim_home,sort=random,limit=1] run summon snow_golem ~0 ~2 ~0 {Tags:[battler,victim]}\\\"}\"}}",    Text4:"{\"text\":\"Snow Golem\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run function restworld:arena/start_battle\"}}"}



execute if score arena_run funcs matches 1 run setblock ~-2 ~2 ~-1.0 air
execute if score arena_run funcs matches 1 run setblock ~-2 ~2 ~-1.0 oak_wall_sign[facing=east]{    Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run scoreboard players set start_battle_type funcs 0\"}}",    Text2:"{\"text\":\"Panda\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~2 ~0 ~0 {Command:\\\"execute if score hunter_count funcs < arena_count funcs at @e[tag=hunter_home,sort=random,limit=1] run summon panda ~0 ~2 ~0 {Tags:[battler,hunter],MainGene:aggressive,Rotation:[180f,0f]}\\\"}\"}}",    Text3:"{\"text\":\"vs.\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~3 ~0 ~0 {Command:\\\"execute if score victim_count funcs < arena_count funcs at @e[tag=victim_home,sort=random,limit=1] run summon vindicator ~0 ~2 ~0 {Tags:[battler,victim],Johnny:True,HandItems:[{id:iron_axe,Count:1},{}]}\\\"}\"}}",    Text4:"{\"text\":\"Vindicator\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run function restworld:arena/start_battle\"}}"}


execute if score arena_run funcs matches 2 run setblock ~-2 ~2 ~2 oak_wall_sign[facing=east]{GlowingText:True,Text2:"{\"text\":\"<--\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_action_home] positioned ~0 ~2 ~0 run scoreboard players set arena_run funcs 1\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=controls_home] run function restworld:arena/arena_run_cur\"}}"}
execute if score arena_run funcs matches 2 run setblock ~-2 ~2 ~-2 oak_wall_sign[facing=east]{GlowingText:True,Text2:"{\"text\":\"-->\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_action_home] positioned ~0 ~2 ~0 run scoreboard players set arena_run funcs 3\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=controls_home] run function restworld:arena/arena_run_cur\"}}"}


execute if score arena_run funcs matches 2 run setblock ~-2 ~3 ~1.0 air
execute if score arena_run funcs matches 2 run setblock ~-2 ~3 ~1.0 oak_wall_sign[facing=east]{    Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run scoreboard players set start_battle_type funcs 0\"}}",    Text2:"{\"text\":\"Parrot\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~2 ~0 ~0 {Command:\\\"execute if score hunter_count funcs < arena_count funcs at @e[tag=hunter_home,sort=random,limit=1] run summon parrot ~0 ~2 ~0 {Tags:[battler,hunter],Rotation:[180f,0f]}\\\"}\"}}",    Text3:"{\"text\":\"vs.\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~3 ~0 ~0 {Command:\\\"execute if score victim_count funcs < arena_count funcs at @e[tag=victim_home,sort=random,limit=1] run summon vindicator ~0 ~2 ~0 {Tags:[battler,victim],Johnny:True,HandItems:[{id:iron_axe,Count:1},{}]}\\\"}\"}}",    Text4:"{\"text\":\"Vindicator\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run function restworld:arena/start_battle\"}}"}



execute if score arena_run funcs matches 2 run setblock ~-2 ~3 ~0.0 air
execute if score arena_run funcs matches 2 run setblock ~-2 ~3 ~0.0 oak_wall_sign[facing=east]{    Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run scoreboard players set start_battle_type funcs 2\"}}",    Text2:"{\"text\":\"Phantom\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~2 ~0 ~0 {Command:\\\"execute if score hunter_count funcs < arena_count funcs at @e[tag=hunter_home,sort=random,limit=1] run summon phantom ~0 ~2 ~0 {Tags:[battler,hunter],AX:1000,AY:110,AZ:-1000,Rotation:[180f,0f]}\\\"}\"}}",    Text3:"{\"text\":\"vs.\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~3 ~0 ~0 {Command:\\\"execute if score victim_count funcs < arena_count funcs at @e[tag=victim_home,sort=random,limit=1] run summon rabbit ~0 ~2 ~0 {Tags:[battler,victim]}\\\"}\"}}",    Text4:"{\"text\":\"Rabbit\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run function restworld:arena/start_battle\"}}"}



execute if score arena_run funcs matches 2 run setblock ~-2 ~3 ~-1.0 air
execute if score arena_run funcs matches 2 run setblock ~-2 ~3 ~-1.0 oak_wall_sign[facing=east]{    Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run scoreboard players set start_battle_type funcs 0\"}}",    Text2:"{\"text\":\"Piglin Brute\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~2 ~0 ~0 {Command:\\\"execute if score hunter_count funcs < arena_count funcs at @e[tag=hunter_home,sort=random,limit=1] run summon piglin_brute ~0 ~2 ~0 {Tags:[battler,hunter],HandItems:[{id:golden_axe,Count:1}],IsImmuneToZombification:True,Rotation:[180f,0f]}\\\"}\"}}",    Text3:"{\"text\":\"vs.\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~3 ~0 ~0 {Command:\\\"execute if score victim_count funcs < arena_count funcs at @e[tag=victim_home,sort=random,limit=1] run summon vindicator ~0 ~2 ~0 {Tags:[battler,victim],Johnny:True,HandItems:[{id:iron_axe,Count:1},{}]}\\\"}\"}}",    Text4:"{\"text\":\"Vindicator\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run function restworld:arena/start_battle\"}}"}



execute if score arena_run funcs matches 2 run setblock ~-2 ~2 ~1.0 air
execute if score arena_run funcs matches 2 run setblock ~-2 ~2 ~1.0 oak_wall_sign[facing=east]{    Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run scoreboard players set start_battle_type funcs 0\"}}",    Text2:"{\"text\":\"Pillager\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~2 ~0 ~0 {Command:\\\"execute if score hunter_count funcs < arena_count funcs at @e[tag=hunter_home,sort=random,limit=1] run summon pillager ~0 ~2 ~0 {Tags:[battler,hunter],HandItems:[{id:crossbow,Count:1},{}],Rotation:[180f,0f]}\\\"}\"}}",    Text3:"{\"text\":\"vs.\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~3 ~0 ~0 {Command:\\\"execute if score victim_count funcs < arena_count funcs at @e[tag=victim_home,sort=random,limit=1] run summon snow_golem ~0 ~2 ~0 {Tags:[battler,victim]}\\\"}\"}}",    Text4:"{\"text\":\"Snow Golem\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run function restworld:arena/start_battle\"}}"}



execute if score arena_run funcs matches 2 run setblock ~-2 ~2 ~0.0 air
execute if score arena_run funcs matches 2 run setblock ~-2 ~2 ~0.0 oak_wall_sign[facing=east]{    Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run scoreboard players set start_battle_type funcs 0\"}}",    Text2:"{\"text\":\"Polar Bear\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~2 ~0 ~0 {Command:\\\"execute if score hunter_count funcs < arena_count funcs at @e[tag=hunter_home,sort=random,limit=1] run summon polar_bear ~0 ~2 ~0 {Tags:[battler,hunter],Rotation:[180f,0f]}\\\"}\"}}",    Text3:"{\"text\":\"vs.\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~3 ~0 ~0 {Command:\\\"execute if score victim_count funcs < arena_count funcs at @e[tag=victim_home,sort=random,limit=1] run summon vindicator ~0 ~2 ~0 {Tags:[battler,victim],Johnny:True,HandItems:[{id:iron_axe,Count:1},{}]}\\\"}\"}}",    Text4:"{\"text\":\"Vindicator\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run function restworld:arena/start_battle\"}}"}



execute if score arena_run funcs matches 2 run setblock ~-2 ~2 ~-1.0 air
execute if score arena_run funcs matches 2 run setblock ~-2 ~2 ~-1.0 oak_wall_sign[facing=east]{    Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run scoreboard players set start_battle_type funcs 0\"}}",    Text2:"{\"text\":\"Ravager\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~2 ~0 ~0 {Command:\\\"execute if score hunter_count funcs < arena_count funcs at @e[tag=hunter_home,sort=random,limit=1] run summon ravager ~0 ~2 ~0 {Tags:[battler,hunter],Rotation:[180f,0f]}\\\"}\"}}",    Text3:"{\"text\":\"vs.\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~3 ~0 ~0 {Command:\\\"execute if score victim_count funcs < arena_count funcs at @e[tag=victim_home,sort=random,limit=1] run summon iron_golem ~0 ~2 ~0 {Tags:[battler,victim]}\\\"}\"}}",    Text4:"{\"text\":\"Iron Golem\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run function restworld:arena/start_battle\"}}"}


execute if score arena_run funcs matches 3 run setblock ~-2 ~2 ~2 oak_wall_sign[facing=east]{GlowingText:True,Text2:"{\"text\":\"<--\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_action_home] positioned ~0 ~2 ~0 run scoreboard players set arena_run funcs 2\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=controls_home] run function restworld:arena/arena_run_cur\"}}"}
execute if score arena_run funcs matches 3 run setblock ~-2 ~2 ~-2 oak_wall_sign[facing=east]{GlowingText:True,Text2:"{\"text\":\"-->\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_action_home] positioned ~0 ~2 ~0 run scoreboard players set arena_run funcs 4\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=controls_home] run function restworld:arena/arena_run_cur\"}}"}


execute if score arena_run funcs matches 3 run setblock ~-2 ~3 ~1.0 air
execute if score arena_run funcs matches 3 run setblock ~-2 ~3 ~1.0 oak_wall_sign[facing=east]{    Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run scoreboard players set start_battle_type funcs 0\"}}",    Text2:"{\"text\":\"Shulker\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~2 ~0 ~0 {Command:\\\"execute if score hunter_count funcs < arena_count funcs at @e[tag=hunter_home,sort=random,limit=1] run summon shulker ~0 ~2 ~0 {Tags:[battler,hunter],Rotation:[180f,0f]}\\\"}\"}}",    Text3:"{\"text\":\"vs.\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~3 ~0 ~0 {Command:\\\"execute if score victim_count funcs < arena_count funcs at @e[tag=victim_home,sort=random,limit=1] run summon vindicator ~0 ~2 ~0 {Tags:[battler,victim],Johnny:True,HandItems:[{id:iron_axe,Count:1},{}]}\\\"}\"}}",    Text4:"{\"text\":\"Vindicator\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run function restworld:arena/start_battle\"}}"}



execute if score arena_run funcs matches 3 run setblock ~-2 ~3 ~0.0 air
execute if score arena_run funcs matches 3 run setblock ~-2 ~3 ~0.0 oak_wall_sign[facing=east]{    Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run scoreboard players set start_battle_type funcs 0\"}}",    Text2:"{\"text\":\"Spider\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~2 ~0 ~0 {Command:\\\"execute if score hunter_count funcs < arena_count funcs at @e[tag=hunter_home,sort=random,limit=1] run summon spider ~0 ~2 ~0 {Tags:[battler,hunter],Rotation:[180f,0f]}\\\"}\"}}",    Text3:"{\"text\":\"vs.\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~3 ~0 ~0 {Command:\\\"execute if score victim_count funcs < arena_count funcs at @e[tag=victim_home,sort=random,limit=1] run summon snow_golem ~0 ~2 ~0 {Tags:[battler,victim]}\\\"}\"}}",    Text4:"{\"text\":\"Snow Golem\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run function restworld:arena/start_battle\"}}"}



execute if score arena_run funcs matches 3 run setblock ~-2 ~3 ~-1.0 air
execute if score arena_run funcs matches 3 run setblock ~-2 ~3 ~-1.0 oak_wall_sign[facing=east]{    Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run scoreboard players set start_battle_type funcs 2\"}}",    Text2:"{\"text\":\"Stray\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~2 ~0 ~0 {Command:\\\"execute if score hunter_count funcs < arena_count funcs at @e[tag=hunter_home,sort=random,limit=1] run summon stray ~0 ~2 ~0 {Tags:[battler,hunter],HandItems:[{id:bow,Count:1}],ArmorItems:[{id:iron_boots,Count:1,tag:{RepairCost:1,Enchantments:[{lvl:9,id:protection}]}},{},{},{}],Rotation:[180f,0f]}\\\"}\"}}",    Text3:"{\"text\":\"vs.\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~3 ~0 ~0 {Command:\\\"execute if score victim_count funcs < arena_count funcs at @e[tag=victim_home,sort=random,limit=1] run summon iron_golem ~0 ~2 ~0 {Tags:[battler,victim]}\\\"}\"}}",    Text4:"{\"text\":\"Iron Golem\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run function restworld:arena/start_battle\"}}"}



execute if score arena_run funcs matches 3 run setblock ~-2 ~2 ~1.0 air
execute if score arena_run funcs matches 3 run setblock ~-2 ~2 ~1.0 oak_wall_sign[facing=east]{    Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run scoreboard players set start_battle_type funcs 0\"}}",    Text2:"{\"text\":\"Vex\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~2 ~0 ~0 {Command:\\\"execute if score hunter_count funcs < arena_count funcs at @e[tag=hunter_home,sort=random,limit=1] run summon vex ~0 ~2 ~0 {Tags:[battler,hunter],Rotation:[180f,0f]}\\\"}\"}}",    Text3:"{\"text\":\"vs.\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~3 ~0 ~0 {Command:\\\"execute if score victim_count funcs < arena_count funcs at @e[tag=victim_home,sort=random,limit=1] run summon snow_golem ~0 ~2 ~0 {Tags:[battler,victim]}\\\"}\"}}",    Text4:"{\"text\":\"Snow Golem\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run function restworld:arena/start_battle\"}}"}



execute if score arena_run funcs matches 3 run setblock ~-2 ~2 ~0.0 air
execute if score arena_run funcs matches 3 run setblock ~-2 ~2 ~0.0 oak_wall_sign[facing=east]{    Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run scoreboard players set start_battle_type funcs 0\"}}",    Text2:"{\"text\":\"Vindicator\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~2 ~0 ~0 {Command:\\\"execute if score hunter_count funcs < arena_count funcs at @e[tag=hunter_home,sort=random,limit=1] run summon vindicator ~0 ~2 ~0 {Tags:[battler,hunter],Johnny:True,HandItems:[{id:iron_axe,Count:1},{}],Rotation:[180f,0f]}\\\"}\"}}",    Text3:"{\"text\":\"vs.\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~3 ~0 ~0 {Command:\\\"execute if score victim_count funcs < arena_count funcs at @e[tag=victim_home,sort=random,limit=1] run summon iron_golem ~0 ~2 ~0 {Tags:[battler,victim]}\\\"}\"}}",    Text4:"{\"text\":\"Iron Golem\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run function restworld:arena/start_battle\"}}"}



execute if score arena_run funcs matches 3 run setblock ~-2 ~2 ~-1.0 air
execute if score arena_run funcs matches 3 run setblock ~-2 ~2 ~-1.0 oak_wall_sign[facing=east]{    Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run scoreboard players set start_battle_type funcs 0\"}}",    Text2:"{\"text\":\"Witch\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~2 ~0 ~0 {Command:\\\"execute if score hunter_count funcs < arena_count funcs at @e[tag=hunter_home,sort=random,limit=1] run summon witch ~0 ~2 ~0 {Tags:[battler,hunter],Rotation:[180f,0f]}\\\"}\"}}",    Text3:"{\"text\":\"vs.\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~3 ~0 ~0 {Command:\\\"execute if score victim_count funcs < arena_count funcs at @e[tag=victim_home,sort=random,limit=1] run summon snow_golem ~0 ~2 ~0 {Tags:[battler,victim]}\\\"}\"}}",    Text4:"{\"text\":\"Snow Golem\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run function restworld:arena/start_battle\"}}"}


execute if score arena_run funcs matches 4 run setblock ~-2 ~2 ~2 oak_wall_sign[facing=east]{GlowingText:True,Text2:"{\"text\":\"<--\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_action_home] positioned ~0 ~2 ~0 run scoreboard players set arena_run funcs 3\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=controls_home] run function restworld:arena/arena_run_cur\"}}"}
execute if score arena_run funcs matches 4 run setblock ~-2 ~2 ~-2 oak_wall_sign[facing=east]{GlowingText:True,Text2:"{\"text\":\"-->\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_action_home] positioned ~0 ~2 ~0 run scoreboard players set arena_run funcs 0\"}}",Text3:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=arena_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=controls_home] run function restworld:arena/arena_run_cur\"}}"}


execute if score arena_run funcs matches 4 run setblock ~-2 ~3 ~1.0 air
execute if score arena_run funcs matches 4 run setblock ~-2 ~3 ~1.0 oak_wall_sign[facing=east]{    Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run scoreboard players set start_battle_type funcs 0\"}}",    Text2:"{\"text\":\"Wither\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~2 ~0 ~0 {Command:\\\"execute if score hunter_count funcs < arena_count funcs at @e[tag=hunter_home,sort=random,limit=1] run summon wither ~0 ~2 ~0 {Tags:[battler,hunter],Rotation:[180f,0f]}\\\"}\"}}",    Text3:"{\"text\":\"vs.\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~3 ~0 ~0 {Command:\\\"execute if score victim_count funcs < arena_count funcs at @e[tag=victim_home,sort=random,limit=1] run summon pillager ~0 ~2 ~0 {Tags:[battler,victim],HandItems:[{id:crossbow,Count:1},{}]}\\\"}\"}}",    Text4:"{\"text\":\"Pillager\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run function restworld:arena/start_battle\"}}"}



execute if score arena_run funcs matches 4 run setblock ~-2 ~3 ~0.0 air
execute if score arena_run funcs matches 4 run setblock ~-2 ~3 ~0.0 oak_wall_sign[facing=east]{    Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run scoreboard players set start_battle_type funcs 0\"}}",    Text2:"{\"text\":\"Wither Skeleton\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~2 ~0 ~0 {Command:\\\"execute if score hunter_count funcs < arena_count funcs at @e[tag=hunter_home,sort=random,limit=1] run summon wither_skeleton ~0 ~2 ~0 {Tags:[battler,hunter],HandItems:[{id:stone_sword,Count:1},{}],Rotation:[180f,0f]}\\\"}\"}}",    Text3:"{\"text\":\"vs.\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~3 ~0 ~0 {Command:\\\"execute if score victim_count funcs < arena_count funcs at @e[tag=victim_home,sort=random,limit=1] run summon piglin ~0 ~2 ~0 {Tags:[battler,victim],IsImmuneToZombification:True,HandItems:[{id:golden_sword,Count:1},{}]}\\\"}\"}}",    Text4:"{\"text\":\"Piglin\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run function restworld:arena/start_battle\"}}"}



execute if score arena_run funcs matches 4 run setblock ~-2 ~3 ~-1.0 air
execute if score arena_run funcs matches 4 run setblock ~-2 ~3 ~-1.0 oak_wall_sign[facing=east]{    Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run scoreboard players set start_battle_type funcs 0\"}}",    Text2:"{\"text\":\"Wolf\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~2 ~0 ~0 {Command:\\\"execute if score hunter_count funcs < arena_count funcs at @e[tag=hunter_home,sort=random,limit=1] run summon wolf ~0 ~2 ~0 {Tags:[battler,hunter],Rotation:[180f,0f]}\\\"}\"}}",    Text3:"{\"text\":\"vs.\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~3 ~0 ~0 {Command:\\\"execute if score victim_count funcs < arena_count funcs at @e[tag=victim_home,sort=random,limit=1] run summon sheep ~0 ~2 ~0 {Tags:[battler,victim]}\\\"}\"}}",    Text4:"{\"text\":\"Sheep\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run function restworld:arena/start_battle\"}}"}



execute if score arena_run funcs matches 4 run setblock ~-2 ~2 ~1.0 air
execute if score arena_run funcs matches 4 run setblock ~-2 ~2 ~1.0 oak_wall_sign[facing=east]{    Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run scoreboard players set start_battle_type funcs 0\"}}",    Text2:"{\"text\":\"Zoglin\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~2 ~0 ~0 {Command:\\\"execute if score hunter_count funcs < arena_count funcs at @e[tag=hunter_home,sort=random,limit=1] run summon zoglin ~0 ~2 ~0 {Tags:[battler,hunter],Rotation:[180f,0f]}\\\"}\"}}",    Text3:"{\"text\":\"vs.\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~3 ~0 ~0 {Command:\\\"execute if score victim_count funcs < arena_count funcs at @e[tag=victim_home,sort=random,limit=1] run summon vindicator ~0 ~2 ~0 {Tags:[battler,victim],Johnny:True,HandItems:[{id:iron_axe,Count:1},{}]}\\\"}\"}}",    Text4:"{\"text\":\"Vindicator\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run function restworld:arena/start_battle\"}}"}



execute if score arena_run funcs matches 4 run setblock ~-2 ~2 ~0.0 air
execute if score arena_run funcs matches 4 run setblock ~-2 ~2 ~0.0 oak_wall_sign[facing=east]{    Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run scoreboard players set start_battle_type funcs 2\"}}",    Text2:"{\"text\":\"Zombie\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~2 ~0 ~0 {Command:\\\"execute if score hunter_count funcs < arena_count funcs at @e[tag=hunter_home,sort=random,limit=1] run summon zombie ~0 ~2 ~0 {Tags:[battler,hunter],Rotation:[180f,0f]}\\\"}\"}}",    Text3:"{\"text\":\"vs.\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~3 ~0 ~0 {Command:\\\"execute if score victim_count funcs < arena_count funcs at @e[tag=victim_home,sort=random,limit=1] run summon iron_golem ~0 ~2 ~0 {Tags:[battler,victim]}\\\"}\"}}",    Text4:"{\"text\":\"Iron Golem\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run function restworld:arena/start_battle\"}}"}



execute if score arena_run funcs matches 4 run setblock ~-2 ~2 ~-1.0 air
execute if score arena_run funcs matches 4 run setblock ~-2 ~2 ~-1.0 oak_wall_sign[facing=east]{    Text1:"{\"text\":\"\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run scoreboard players set start_battle_type funcs 0\"}}",    Text2:"{\"text\":\"Zombified Piglin\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~2 ~0 ~0 {Command:\\\"execute if score hunter_count funcs < arena_count funcs at @e[tag=hunter_home,sort=random,limit=1] run summon zombified_piglin ~0 ~2 ~0 {Tags:[battler,hunter],HandItems:[{id:golden_sword,Count:1}],Rotation:[180f,0f]}\\\"}\"}}",    Text3:"{\"text\":\"vs.\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run execute at @e[tag=monitor_home] run data merge block ~3 ~0 ~0 {Command:\\\"execute if score victim_count funcs < arena_count funcs at @e[tag=victim_home,sort=random,limit=1] run summon vindicator ~0 ~2 ~0 {Tags:[battler,victim],Johnny:True,HandItems:[{id:iron_axe,Count:1},{}]}\\\"}\"}}",    Text4:"{\"text\":\"Vindicator\",\"clickEvent\":{\"action\":\"run_command\",\"value\":\"execute at @e[tag=controls_action_home] positioned ~0 ~2 ~0 run function restworld:arena/start_battle\"}}"}
